/-
Copyright (c) 2026 Shanwen Wang, Yijun Yuan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yijun Yuan
-/
module

public import TrustworthyKedlaya.Kedlaya.TowerEmbedding

/-!
# Fractional-integral supports are algebraic

Every Hahn series in `𝔽̄_p((t^ℚ))` whose support lies in `(1/n) ℤ` is integral — in
particular algebraic — over the Laurent field `𝔽̄_p((t))` (Kedlaya (2001a), proof of
Theorem 8).  Writing each exponent as `k/n + m` with `0 ≤ k < n` and
`m ∈ ℤ` decomposes the series as `∑_{k<n} t^{k/n}·x_k` with `x_k` a Laurent series, so
the series lies in the subalgebra generated by `t^{1/n}`, which is integral (a root of
`Z^n - t`); elements of the resulting finite module are integral.

## Main statements

- `TrustworthyKedlaya.UP.intSupportedPreimage` /
  `TrustworthyKedlaya.UP.intHahnEmbedding_intSupportedPreimage`: a Hahn series with
  integer support is the image of a Laurent series under `intHahnEmbedding`.
- `TrustworthyKedlaya.UP.isIntegral_hahn_of_support_int_div` /
  `TrustworthyKedlaya.UP.isAlgebraic_hahn_of_support_int_div`: the fractional-Laurent
  algebraicity lemma.

## References

- K. S. Kedlaya, *The algebraic closure of the power series field in positive
  characteristic*, Proc. Amer. Math. Soc. 129 (2001) [Ked01a], proof of Theorem 8.
-/

@[expose] public section

namespace TrustworthyKedlaya.UP

open LaurentSeries

variable {p : ℕ} [hp : Fact (Nat.Prime p)]

/-- Pull a Hahn series over `ℚ` back to a Laurent series by reading off the
coefficients at the integer exponents.  Left inverse to `intHahnEmbedding` on series
supported on the integers (`intHahnEmbedding_intSupportedPreimage`). -/
noncomputable def intSupportedPreimage (x : HahnSeries ℚ (𝔽ᵃ_[p])) : (𝔽ᵃ_[p])⸨X⸩ where
  coeff m := x.coeff (m : ℚ)
  isPWO_support' := by
    refine Set.IsWF.isPWO ?_
    rw [Set.isWF_iff_no_descending_seq]
    intro f hf hmem
    have hanti : StrictAnti fun k => ((f k : ℤ) : ℚ) := fun a b hab => by
      change ((f b : ℤ) : ℚ) < ((f a : ℤ) : ℚ)
      exact_mod_cast hf hab
    have hx := x.isWF_support
    rw [Set.isWF_iff_no_descending_seq] at hx
    exact hx _ hanti fun k => hmem k

@[simp] theorem coeff_intSupportedPreimage (x : HahnSeries ℚ (𝔽ᵃ_[p])) (m : ℤ) :
    (intSupportedPreimage x).coeff m = x.coeff (m : ℚ) := rfl

/-- A Hahn series supported on the integers is the image of a Laurent series under
`intHahnEmbedding`. -/
theorem intHahnEmbedding_intSupportedPreimage {x : HahnSeries ℚ (𝔽ᵃ_[p])}
    (hx : ∀ s ∈ x.support, ∃ m : ℤ, s = (m : ℚ)) :
    intHahnEmbedding p (intSupportedPreimage x) = x := by
  refine HahnSeries.ext (funext fun s => ?_)
  by_cases hs : s ∈ Set.range ((Int.castAddHom ℚ : ℤ →+ ℚ))
  · obtain ⟨m, rfl⟩ := hs
    exact HahnSeries.embDomain_coeff
  · have hL : (intHahnEmbedding p (intSupportedPreimage x)).coeff s = 0 :=
      HahnSeries.embDomain_of_notMem_range hs
    have hR : x.coeff s = 0 := by
      by_contra h0
      obtain ⟨m, hm⟩ := hx s h0
      exact hs ⟨m, hm.symm⟩
    rw [hL, hR]

/-- The root monomial `t^{1/n}` is integral over the Laurent field: it is a root of
`Z^n - t`. -/
theorem isIntegral_single_inv_natCast (n : ℕ+) :
    IsIntegral ((𝔽ᵃ_[p])⸨X⸩)
      (HahnSeries.single ((n : ℚ)⁻¹) (1 : 𝔽ᵃ_[p]) : HahnSeries ℚ (𝔽ᵃ_[p])) := by
  have hn : ((n : ℕ) : ℚ) ≠ 0 := by exact_mod_cast n.pos.ne'
  refine ⟨Polynomial.X ^ (n : ℕ)
    - Polynomial.C (HahnSeries.single (1 : ℤ) (1 : 𝔽ᵃ_[p])),
    Polynomial.monic_X_pow_sub_C _ n.pos.ne', ?_⟩
  simp only [Polynomial.eval₂_sub, Polynomial.eval₂_X_pow, Polynomial.eval₂_C]
  have hpow : (HahnSeries.single ((n : ℚ)⁻¹) (1 : 𝔽ᵃ_[p])) ^ (n : ℕ)
      = HahnSeries.single (1 : ℚ) (1 : 𝔽ᵃ_[p]) := by
    rw [single_pow, one_pow, mul_inv_cancel₀ hn]
  have hemb : algebraMap ((𝔽ᵃ_[p])⸨X⸩) (HahnSeries ℚ (𝔽ᵃ_[p]))
      (HahnSeries.single (1 : ℤ) (1 : 𝔽ᵃ_[p]))
      = HahnSeries.single (1 : ℚ) (1 : 𝔽ᵃ_[p]) := by
    have h1 := intHahnEmbedding_single p (g := 1) (r := (1 : 𝔽ᵃ_[p]))
    exact h1.trans (by norm_num)
  rw [hpow, hemb, sub_self]

/-- **Fractional-integral supports are algebraic**, integral form: every Hahn series
with support contained in `(1/n) ℤ` is integral over the Laurent field `𝔽̄_p((t))`. -/
theorem isIntegral_hahn_of_support_int_div (n : ℕ+) {x : HahnSeries ℚ (𝔽ᵃ_[p])}
    (hsupp : ∀ s ∈ x.support, ∃ k : ℤ, s = (k : ℚ) / (n : ℚ)) :
    IsIntegral ((𝔽ᵃ_[p])⸨X⸩) x := by
  have hn : ((n : ℕ) : ℚ) ≠ 0 := by exact_mod_cast n.pos.ne'
  -- The residue classes of exponents modulo the integers.
  set S : ℕ → Set ℚ := fun k => {s : ℚ | ∃ m : ℤ, s = (k : ℚ) / (n : ℚ) + m} with hS
  -- The series decomposes along the residue classes.
  have hdecomp : x = ∑ k ∈ Finset.range (n : ℕ), hahnRestrict (S k) x := by
    refine HahnSeries.ext (funext fun s => ?_)
    rw [HahnSeries.coeff_sum]
    by_cases h0 : x.coeff s = 0
    · rw [h0]
      refine (Finset.sum_eq_zero fun k _ => ?_).symm
      by_cases hks : s ∈ S k
      · rw [coeff_hahnRestrict_of_mem x hks, h0]
      · rw [coeff_hahnRestrict_of_notMem x hks]
    · obtain ⟨j, hj⟩ := hsupp s h0
      have hnz : ((n : ℕ) : ℤ) ≠ 0 := by exact_mod_cast n.pos.ne'
      set k₀ : ℕ := (j % ((n : ℕ) : ℤ)).toNat with hk₀
      have hjmod0 : (0 : ℤ) ≤ j % ((n : ℕ) : ℤ) := Int.emod_nonneg j hnz
      have hjmodlt : j % ((n : ℕ) : ℤ) < ((n : ℕ) : ℤ) :=
        Int.emod_lt_of_pos j (by exact_mod_cast n.pos)
      have hk₀cast : ((k₀ : ℤ)) = j % ((n : ℕ) : ℤ) := Int.toNat_of_nonneg hjmod0
      have hmem : s ∈ S k₀ := by
        refine ⟨j / ((n : ℕ) : ℤ), ?_⟩
        have hdm : (k₀ : ℤ) + ((n : ℕ) : ℤ) * (j / ((n : ℕ) : ℤ)) = j := by
          rw [hk₀cast, Int.emod_def]
          ring
        have hq : (j : ℚ) = (k₀ : ℚ) + (n : ℚ) * ((j / ((n : ℕ) : ℤ) : ℤ) : ℚ) := by
          exact_mod_cast congrArg (fun t : ℤ => (t : ℚ)) hdm.symm
        rw [hj, hq]
        field_simp
      have hothers : ∀ b ∈ Finset.range (n : ℕ), b ≠ k₀ →
          (hahnRestrict (S b) x).coeff s = 0 := by
        intro b hb hbne
        by_cases hbs : s ∈ S b
        · exfalso
          obtain ⟨m, hm⟩ := hbs
          rw [hj] at hm
          have hint : j = (b : ℤ) + ((n : ℕ) : ℤ) * m := by
            have h1 : (j : ℚ) = (b : ℚ) + (n : ℚ) * (m : ℚ) := by
              field_simp at hm
              linarith [hm]
            exact_mod_cast h1
          have hb' : b < (n : ℕ) := Finset.mem_range.mp hb
          have hbmod : j % ((n : ℕ) : ℤ) = (b : ℤ) := by
            rw [hint, Int.add_mul_emod_self_left]
            exact Int.emod_eq_of_lt (by positivity) (by exact_mod_cast hb')
          exact hbne (by omega)
        · exact coeff_hahnRestrict_of_notMem x hbs
      rw [Finset.sum_eq_single k₀ hothers
          (fun hout => absurd (Finset.mem_range.mpr (by omega)) hout),
        coeff_hahnRestrict_of_mem x hmem]
  -- Each residue-class piece is a monomial times a Laurent series.
  have hpiece : ∀ k : ℕ,
      hahnRestrict (S k) x
        = (HahnSeries.single ((n : ℚ)⁻¹) (1 : 𝔽ᵃ_[p])) ^ k
          * intHahnEmbedding p (intSupportedPreimage
              (HahnSeries.single (-((k : ℚ) / (n : ℚ))) 1 * hahnRestrict (S k) x)) := by
    intro k
    have hshift : ∀ s' ∈ (HahnSeries.single (-((k : ℚ) / (n : ℚ))) (1 : 𝔽ᵃ_[p])
        * hahnRestrict (S k) x).support, ∃ m : ℤ, s' = (m : ℚ) := by
      intro s' hs'
      rw [HahnSeries.mem_support, HahnSeries.coeff_single_mul, one_mul, sub_neg_eq_add] at hs'
      have hmem := support_hahnRestrict_subset_set (S k) x (HahnSeries.mem_support _ _ |>.mpr hs')
      obtain ⟨m, hm⟩ := hmem
      exact ⟨m, by linarith [hm]⟩
    rw [intHahnEmbedding_intSupportedPreimage hshift, single_pow, one_pow, ← mul_assoc,
      HahnSeries.single_mul_single, one_mul]
    have hexp : (k : ℚ) * (n : ℚ)⁻¹ + -((k : ℚ) / (n : ℚ)) = 0 := by
      rw [← div_eq_mul_inv]
      ring
    rw [hexp, HahnSeries.single_zero_one, one_mul]
  -- Hence `x` lies in the subalgebra generated by the integral element `t^{1/n}`.
  have hmem : x ∈ Algebra.adjoin ((𝔽ᵃ_[p])⸨X⸩)
      {(HahnSeries.single ((n : ℚ)⁻¹) (1 : 𝔽ᵃ_[p]) : HahnSeries ℚ (𝔽ᵃ_[p]))} := by
    rw [hdecomp]
    refine Subalgebra.sum_mem _ fun k _ => ?_
    rw [hpiece k]
    exact Subalgebra.mul_mem _
      (Subalgebra.pow_mem _ (Algebra.self_mem_adjoin_singleton _ _) k)
      (Subalgebra.algebraMap_mem _ _)
  exact IsIntegral.of_mem_of_fg _ (isIntegral_single_inv_natCast n).fg_adjoin_singleton _ hmem

/-- **Fractional-integral supports are algebraic**: every Hahn series with support
contained in `(1/n) ℤ` is algebraic over the Laurent field `𝔽̄_p((t))`. -/
theorem isAlgebraic_hahn_of_support_int_div (n : ℕ+) {x : HahnSeries ℚ (𝔽ᵃ_[p])}
    (hsupp : ∀ s ∈ x.support, ∃ k : ℤ, s = (k : ℚ) / (n : ℚ)) :
    IsAlgebraic ((𝔽ᵃ_[p])⸨X⸩) x :=
  (isIntegral_hahn_of_support_int_div n hsupp).isAlgebraic

end TrustworthyKedlaya.UP
