/-
Copyright (c) 2026 Yijun Yuan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yijun Yuan
-/
module

public import Mathlib.FieldTheory.Galois.Basic
public import Mathlib.RingTheory.Trace.Basic

/-!
# Degree-`p` Galois extensions in characteristic `p` are Artin–Schreier

Let `F` be a field of characteristic `p` and `E/F` a Galois extension of degree `p`.
This file proves that `E = F(θ)` for an element `θ` with `θ^p - θ ∈ F`
(`TrustworthyKedlaya.exists_artinSchreier_generator`).

The proof is the classical additive-Hilbert-90 argument: the Galois group is cyclic of
order `p`, generated by any `σ ≠ 1`; by separability the trace map is surjective, so
there is `c : E` with `Tr(c) = ∑_{i<p} σ^i c = 1`; the weighted sum
`θ = -∑_{i<p} i · σ^i c` then satisfies `σ θ = θ + 1`, so `θ ∉ F` while
`θ^p - θ` is fixed by the whole group, hence lies in `F`; finally `[F(θ):F]`
divides the prime `p` and is not `1`, so `F(θ) = E`.

This is Lemma `lem:degree-p-artin-schreier` of the blueprint (Kedlaya 2001a, proof of
Lemma 3).
-/

@[expose] public section

namespace TrustworthyKedlaya

open Finset IntermediateField

variable {F E : Type*} [Field F] [Field E] [Algebra F E]

/-- **Degree-`p` Galois extensions are Artin–Schreier**: if `F` has characteristic `p`
and `E/F` is Galois of degree `p`, then `E = F(θ)` with `θ^p - θ ∈ F`. -/
theorem exists_artinSchreier_generator (p : ℕ) [Fact p.Prime] [CharP F p] [IsGalois F E]
    (hrank : Module.finrank F E = p) :
    ∃ θ : E, F⟮θ⟯ = ⊤ ∧ θ ^ p - θ ∈ (algebraMap F E).range := by
  have hp : p.Prime := Fact.out
  have : FiniteDimensional F E := FiniteDimensional.of_finrank_pos (hrank ▸ hp.pos)
  have : CharP E p := charP_of_injective_algebraMap (algebraMap F E).injective p
  have : ExpChar E p := .prime hp
  -- The Galois group has prime order `p`; any `σ ≠ 1` has order `p`.
  have hcard : Fintype.card (E ≃ₐ[F] E) = p := by
    rw [← Nat.card_eq_fintype_card, IsGalois.card_aut_eq_finrank F E, hrank]
  have : Nontrivial (E ≃ₐ[F] E) := Fintype.one_lt_card_iff_nontrivial.mp (hcard ▸ hp.one_lt)
  obtain ⟨σ, hσ1⟩ := exists_ne (1 : E ≃ₐ[F] E)
  have hσp : orderOf σ = p := orderOf_eq_prime (hcard ▸ pow_card_eq_one) hσ1
  have hσpow : σ ^ p = 1 := hcard ▸ pow_card_eq_one
  -- The powers `σ^0, …, σ^{p-1}` exhaust the group.
  have hbij : Function.Bijective (fun i : Fin p => σ ^ (i : ℕ)) := by
    rw [Fintype.bijective_iff_injective_and_card]
    exact ⟨fun i j hij => Fin.ext (pow_injOn_Iio_orderOf
        (by simp [hσp]) (by simp [hσp]) hij),
      (Fintype.card_fin p).trans hcard.symm⟩
  -- An element of trace one, and its power sum.
  obtain ⟨c, hc⟩ := Algebra.trace_surjective F E (1 : F)
  have hT : ∑ i ∈ range p, (σ ^ i) c = 1 := by
    calc ∑ i ∈ range p, (σ ^ i) c
        = ∑ i : Fin p, (σ ^ (i : ℕ)) c := (Fin.sum_univ_eq_sum_range (fun j => (σ ^ j) c) p).symm
      _ = ∑ g : E ≃ₐ[F] E, g c := hbij.sum_comp (fun g => g c)
      _ = 1 := by rw [← trace_eq_sum_automorphisms, hc, map_one]
  -- The Artin–Schreier generator.
  set θ : E := -∑ i ∈ range p, (i : E) * (σ ^ i) c with hθ
  have hkey : σ θ = θ + 1 := by
    have hf0 : ∑ j ∈ range (p + 1), (j : E) * (σ ^ j) c = ∑ i ∈ range p, (i : E) * (σ ^ i) c := by
      rw [sum_range_succ, CharP.cast_eq_zero E p, zero_mul, add_zero]
    have hg0 : ∑ j ∈ range (p + 1), (σ ^ j) c = 1 + c := by
      rw [sum_range_succ, hT, hσpow, AlgEquiv.one_apply]
    have hσθ : σ (∑ i ∈ range p, (i : E) * (σ ^ i) c)
        = ∑ i ∈ range p, (i : E) * (σ ^ (i + 1)) c := by
      rw [map_sum]
      exact Finset.sum_congr rfl fun i _ => by
        rw [map_mul, map_natCast, pow_succ', AlgEquiv.mul_apply]
    have hsplit : ∑ i ∈ range p, (i : E) * (σ ^ (i + 1)) c
        = (∑ i ∈ range p, ((i + 1 : ℕ) : E) * (σ ^ (i + 1)) c)
          - ∑ i ∈ range p, (σ ^ (i + 1)) c := by
      rw [← Finset.sum_sub_distrib]
      exact Finset.sum_congr rfl fun i _ => by push_cast; ring
    have hfshift : ∑ i ∈ range p, ((i + 1 : ℕ) : E) * (σ ^ (i + 1)) c
        = ∑ i ∈ range p, (i : E) * (σ ^ i) c := by
      rw [← hf0, Finset.sum_range_succ' (fun j => (j : E) * (σ ^ j) c) p]
      simp
    have hgshift : ∑ i ∈ range p, (σ ^ (i + 1)) c = 1 := by
      have := Finset.sum_range_succ' (fun j => (σ ^ j) c) p
      rw [hg0] at this
      simpa using this.symm
    rw [hθ, map_neg, hσθ, hsplit, hfshift, hgshift]
    ring
  -- `θ^p - θ` is fixed by `σ`, hence by the whole Galois group, hence lies in `F`.
  have hσfix : σ (θ ^ p - θ) = θ ^ p - θ := by
    rw [map_sub, map_pow, hkey, add_pow_char, one_pow, add_sub_add_right_eq_sub]
  have hfix : ∀ g : E ≃ₐ[F] E, g (θ ^ p - θ) = θ ^ p - θ := by
    have hpow : ∀ n : ℕ, (σ ^ n) (θ ^ p - θ) = θ ^ p - θ := by
      intro n
      induction n with
      | zero => rw [pow_zero, AlgEquiv.one_apply]
      | succ n ih => rw [pow_succ', AlgEquiv.mul_apply, ih, hσfix]
    intro g
    obtain ⟨i, rfl⟩ := hbij.surjective g
    exact hpow i
  have hmem : θ ^ p - θ ∈ (algebraMap F E).range := by
    have := (IsGalois.mem_bot_iff_fixed (θ ^ p - θ)).mpr hfix
    rwa [IntermediateField.mem_bot] at this
  -- `θ` is moved by `σ`, so it does not lie in `F`; hence it generates `E`.
  have hnotbot : θ ∉ (⊥ : IntermediateField F E) := by
    intro h
    rw [IntermediateField.mem_bot] at h
    obtain ⟨x, hx⟩ := h
    have hfixθ := σ.commutes x
    rw [hx, hkey] at hfixθ
    simp at hfixθ
  refine ⟨θ, ?_, hmem⟩
  have htower : Module.finrank F F⟮θ⟯ * Module.finrank F⟮θ⟯ E = p := by
    rw [Module.finrank_mul_finrank, hrank]
  rcases hp.eq_one_or_self_of_dvd _ (Dvd.intro_left _ htower) with h1 | hpp
  · exact IntermediateField.finrank_eq_one_iff_eq_top.mp h1
  · exfalso
    rw [hpp] at htower
    have hone : Module.finrank F F⟮θ⟯ = 1 :=
      Nat.eq_of_mul_eq_mul_right hp.pos (htower.trans (one_mul p).symm)
    exact hnotbot (IntermediateField.finrank_eq_one_iff.mp hone ▸
      IntermediateField.mem_adjoin_simple_self F θ)

end TrustworthyKedlaya
