/-
Copyright (c) 2026 Yijun Yuan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yijun Yuan
-/
module

public import Mathlib.Analysis.Normed.Unbundled.SpectralNorm
public import Mathlib.RingTheory.LaurentSeries
public import Mathlib.RingTheory.Valuation.Discrete.RankOne
public import Mathlib.Topology.Algebra.Valued.NormedValued

/-!
# Finite extensions of `K⸨X⸩` are complete discretely valued

Let `B = K⸨X⸩` be the Laurent-series field over a field `K`, with its `X`-adic
valuation. This file equips `B` with the corresponding normed-field structure and
shows that for every finite field extension `L/B`:

* the norm (equivalently, the `X`-adic valuation) extends uniquely to `L`
  (via the spectral norm);
* `L` is complete;
* the value group of `L` is `q^{(1/e)ℤ}` for some `e ∣ [L:B]`;
* when `K` is algebraically closed, the residue field of `L` is `K` and the
  extension is totally ramified (`e = [L:B]`).

This is Lemma `lem:ext-valuation` of the blueprint (Kedlaya 2001a, §3).
-/

@[expose] public section

namespace TrustworthyKedlaya.Ext

open LaurentSeries Valuation
open scoped WithZero

variable (K : Type*) [Field K]

/-- The `X`-adic valuation on `K⸨X⸩` is rank-one discrete. -/
instance : (Valued.v : Valuation K⸨X⸩ ℤᵐ⁰).IsRankOneDiscrete where
  exists_generator_lt_one' := by
    refine ⟨Units.mk0 (WithZero.exp (-1)) WithZero.exp_ne_zero, ?_, ?_⟩
    · have htop : (MonoidWithZeroHom.ofClass (Valued.v : Valuation K⸨X⸩ ℤᵐ⁰)).valueGroup = ⊤ := by
        rw [Subgroup.eq_top_iff']
        intro u
        exact MonoidWithZeroHom.mem_valueGroup _ (LaurentSeries.valuation_surjective K u.1)
      rw [htop, Subgroup.eq_top_iff']
      intro u
      rw [Subgroup.mem_zpowers_iff]
      refine ⟨-WithZero.log u.1, Units.ext ?_⟩
      rw [Units.val_zpow_eq_zpow_val, Units.val_mk0, ← WithZero.exp_zsmul, smul_neg, smul_eq_mul,
        mul_one, neg_neg, WithZero.exp_log u.ne_zero]
    · rw [← Units.val_lt_val, Units.val_mk0, Units.val_one, ← WithZero.exp_zero]
      exact WithZero.exp_lt_exp.mpr (by norm_num)

/-- A rank-one structure on the `X`-adic valuation of `K⸨X⸩` (with normalization
`‖X‖ = 1/2`; only the induced topology matters). -/
noncomputable instance : (Valued.v : Valuation K⸨X⸩ ℤᵐ⁰).RankOne :=
  IsRankOneDiscrete.rankOne _ one_lt_two

open scoped Valued

section BaseField

variable {K}

/-- Two Laurent series with the same valuation have the same norm. -/
theorem norm_eq_of_valuation_eq {f g : K⸨X⸩} (h : Valued.v f = Valued.v g) : ‖f‖ = ‖g‖ :=
  le_antisymm (Valued.toNormedField.norm_le_iff.mpr h.le)
    (Valued.toNormedField.norm_le_iff.mpr h.ge)

/-- The norm of `X` in `K⸨X⸩` is strictly between `0` and `1`. -/
theorem norm_X_pos : 0 < ‖(HahnSeries.single 1 1 : K⸨X⸩)‖ := by
  rw [norm_pos_iff]
  exact HahnSeries.single_ne_zero one_ne_zero

theorem norm_X_lt_one : ‖(HahnSeries.single 1 1 : K⸨X⸩)‖ < 1 := by
  rw [Valued.toNormedField.norm_lt_one_iff, LaurentSeries.valuation_single_zpow,
    ← WithZero.exp_zero]
  exact WithZero.exp_lt_exp.mpr (by norm_num)

/-- The value group of `K⸨X⸩` is generated by the norm of `X`: every nonzero
Laurent series has norm an integer power of `‖X‖`. -/
theorem exists_norm_eq_zpow (f : K⸨X⸩) (hf : f ≠ 0) :
    ∃ m : ℤ, ‖f‖ = ‖(HahnSeries.single 1 1 : K⸨X⸩)‖ ^ m := by
  have hv : Valued.v f ≠ (0 : ℤᵐ⁰) := (Valuation.ne_zero_iff _).mpr hf
  refine ⟨-WithZero.log (Valued.v f), ?_⟩
  rw [← norm_zpow]
  refine norm_eq_of_valuation_eq ?_
  rw [map_zpow₀, LaurentSeries.valuation_single_zpow, ← WithZero.exp_zsmul]
  rw [← WithZero.exp_log hv]
  congr 1
  simp

end BaseField

section Extension

variable {K} {L : Type*} [Field L] [Algebra K⸨X⸩ L] [Module.Finite K⸨X⸩ L]

/-- **Uniqueness of the extended absolute value**: any absolute value on a finite
extension `L` of `K⸨X⸩` restricting to the `X`-adic norm on `K⸨X⸩` coincides with
the spectral norm. -/
theorem absoluteValue_eq_spectralNorm (f : AbsoluteValue L ℝ)
    (hf : ∀ b : K⸨X⸩, f (algebraMap K⸨X⸩ L b) = ‖b‖) (x : L) :
    f x = spectralNorm K⸨X⸩ L x :=
  spectralNorm_unique_field_norm_ext hf x

/-- The `[L : K⸨X⸩]`-th power of the spectral norm of a nonzero element of a finite
extension of `K⸨X⸩` lies in the value group `‖X‖^ℤ` of the base field. -/
theorem spectralNorm_pow_finrank_eq_zpow (x : L) (hx : x ≠ 0) :
    ∃ m : ℤ, spectralNorm K⸨X⸩ L x ^ Module.finrank K⸨X⸩ L =
      ‖(HahnSeries.single 1 1 : K⸨X⸩)‖ ^ m := by
  have hint : IsIntegral K⸨X⸩ x := Algebra.IsIntegral.isIntegral x
  have hn_pos : 0 < (minpoly K⸨X⸩ x).natDegree := minpoly.natDegree_pos hint
  obtain ⟨k, hk⟩ : (minpoly K⸨X⸩ x).natDegree ∣ Module.finrank K⸨X⸩ L :=
    minpoly.degree_dvd hint
  have ha0 : (minpoly K⸨X⸩ x).coeff 0 ≠ 0 := minpoly.coeff_zero_ne_zero hint hx
  obtain ⟨m₀, hm₀⟩ := exists_norm_eq_zpow _ ha0
  refine ⟨m₀ * k, ?_⟩
  rw [spectralNorm.spectralNorm_eq_norm_coeff_zero_rpow, hk, ← Real.rpow_natCast
    (‖(minpoly K⸨X⸩ x).coeff 0‖ ^ (1 / ((minpoly K⸨X⸩ x).natDegree : ℝ))) _,
    ← Real.rpow_mul (norm_nonneg _)]
  have hexp : 1 / ((minpoly K⸨X⸩ x).natDegree : ℝ) *
      (((minpoly K⸨X⸩ x).natDegree * k : ℕ) : ℝ) = (k : ℝ) := by
    have : ((minpoly K⸨X⸩ x).natDegree : ℝ) ≠ 0 := by exact_mod_cast hn_pos.ne'
    push_cast
    field_simp
  rw [hexp, Real.rpow_natCast, hm₀, ← zpow_natCast, ← zpow_mul]

/-- **The value group of a finite extension of `K⸨X⸩` is discrete**: there are `e ∣ [L : K⸨X⸩]`
and a uniformizing element `π` with `‖π‖^e = ‖X‖` such that every nonzero element of `L` has
spectral norm an integer power of `‖π‖`. In particular the value group of `L` is `‖X‖^{(1/e)ℤ}`
and the ramification index divides the degree. -/
theorem exists_spectralNorm_uniformizer :
    ∃ (e : ℕ) (π : L), 0 < e ∧ e ∣ Module.finrank K⸨X⸩ L ∧
      spectralNorm K⸨X⸩ L π ^ e = ‖(HahnSeries.single 1 1 : K⸨X⸩)‖ ∧
      ∀ x : L, x ≠ 0 → ∃ m : ℤ, spectralNorm K⸨X⸩ L x = spectralNorm K⸨X⸩ L π ^ m := by
  let _ : NormedField L := spectralNorm.normedField K⸨X⸩ L
  have hnorm : ∀ y : L, ‖y‖ = spectralNorm K⸨X⸩ L y := fun _ => rfl
  set q : ℝ := ‖(HahnSeries.single 1 1 : K⸨X⸩)‖ with hq
  have hq0 : 0 < q := norm_X_pos
  have hq1 : q < 1 := norm_X_lt_one
  set d : ℕ := Module.finrank K⸨X⸩ L with hd
  have hd0 : 0 < d := Module.finrank_pos
  -- the group of achieved exponents: `m ∈ H` iff some nonzero `x` has `‖x‖^d = q^m`
  set H : AddSubgroup ℤ :=
    { carrier := {m : ℤ | ∃ x : L, x ≠ 0 ∧ ‖x‖ ^ d = q ^ m}
      zero_mem' := ⟨1, one_ne_zero, by simp⟩
      add_mem' := by
        rintro a b ⟨x, hx, hxa⟩ ⟨y, hy, hyb⟩
        exact ⟨x * y, mul_ne_zero hx hy, by
          rw [norm_mul, mul_pow, hxa, hyb, ← zpow_add₀ hq0.ne']⟩
      neg_mem' := by
        rintro a ⟨x, hx, hxa⟩
        exact ⟨x⁻¹, inv_ne_zero hx, by
          rw [norm_inv, inv_pow, hxa, ← zpow_neg]⟩ } with hH
  have hdH : (d : ℤ) ∈ H := by
    refine ⟨algebraMap K⸨X⸩ L (HahnSeries.single 1 1), ?_, ?_⟩
    · simp
    · rw [hnorm, spectralNorm_extends, ← hq, zpow_natCast]
  obtain ⟨g, hg⟩ := Int.subgroup_cyclic H
  -- normalize the generator to be positive
  have hg_mem : g ∈ H := hg ▸ AddSubgroup.mem_closure_singleton.mpr ⟨1, one_smul _ _⟩
  have hgd : g ∣ (d : ℤ) := by
    obtain ⟨k, hk⟩ := AddSubgroup.mem_closure_singleton.mp (hg ▸ hdH)
    exact ⟨k, by rw [← hk, smul_eq_mul, mul_comm]⟩
  have hg0 : g ≠ 0 := by
    rintro rfl
    exact hd0.ne' (by exact_mod_cast (zero_dvd_iff.mp hgd))
  have hdvd_all : ∀ m ∈ H, g ∣ m := by
    intro m hm
    obtain ⟨k, hk⟩ := AddSubgroup.mem_closure_singleton.mp (hg ▸ hm)
    exact ⟨k, by rw [← hk, smul_eq_mul, mul_comm]⟩
  -- pass to the positive generator `gn = |g|`
  set gn : ℕ := g.natAbs with hgn
  have hgn0 : 0 < gn := Int.natAbs_pos.mpr hg0
  have hgn_mem : (gn : ℤ) ∈ H := by
    rcases Int.natAbs_eq g with h | h
    · exact h ▸ hg_mem
    · have hng : ((gn : ℤ)) = -g := by omega
      rw [hng]
      exact H.neg_mem hg_mem
  have hgn_dvd : ∀ m ∈ H, (gn : ℤ) ∣ m := fun m hm =>
    (Int.natAbs_dvd.mpr (hdvd_all m hm))
  obtain ⟨e, he⟩ : gn ∣ d := Int.ofNat_dvd.mp (Int.natAbs_dvd.mpr hgd)
  have he0 : 0 < e := by
    rcases Nat.eq_zero_or_pos e with rfl | h
    · exact absurd (by simpa using he) hd0.ne'
    · exact h
  obtain ⟨π, hπ0, hπ⟩ := hgn_mem
  have hπ_pos : 0 < ‖π‖ := norm_pos_iff.mpr hπ0
  refine ⟨e, π, he0, ⟨gn, by rw [he, mul_comm]⟩, ?_, ?_⟩
  · -- `‖π‖ ^ e = q`, by taking `gn`-th roots of `‖π‖ ^ d = q ^ gn`
    rw [← hnorm]
    refine (pow_left_strictMonoOn₀ (M₀ := ℝ) (n := gn) hgn0.ne').injOn
      (pow_nonneg hπ_pos.le _) hq0.le ?_
    rw [← pow_mul, mul_comm e gn, ← he, hπ, zpow_natCast]
  · -- every nonzero `x` has norm a power of `‖π‖`
    intro x hx
    obtain ⟨m, hm⟩ := spectralNorm_pow_finrank_eq_zpow (K := K) x hx
    rw [← hnorm, ← hnorm] at *
    have hmH : m ∈ H := ⟨x, hx, hm⟩
    obtain ⟨j, hj⟩ := hgn_dvd m hmH
    refine ⟨j, ?_⟩
    have hx_pos : 0 < ‖x‖ := norm_pos_iff.mpr hx
    refine (pow_left_strictMonoOn₀ (M₀ := ℝ) (n := d) hd0.ne').injOn
      hx_pos.le (zpow_nonneg hπ_pos.le _) ?_
    rw [hm, hj, zpow_mul, ← hπ, ← zpow_natCast ‖π‖ d, ← zpow_mul,
      ← zpow_natCast (‖π‖ ^ j) d, ← zpow_mul, mul_comm]

end Extension

end TrustworthyKedlaya.Ext
