/-
Copyright (c) 2026 Yijun Yuan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yijun Yuan
-/
module

public import Mathlib.Analysis.Normed.Unbundled.SpectralNorm
public import Mathlib.RingTheory.LaurentSeries
public import Mathlib.RingTheory.Valuation.Discrete.RankOne
public import Mathlib.Topology.Algebra.Valued.NormedValued

/-!
# Finite extensions of `K⸨X⸩` are complete discretely valued

Let `B = K⸨X⸩` be the Laurent-series field over a field `K`, with its `X`-adic
valuation. This file equips `B` with the corresponding normed-field structure and
shows that for every finite field extension `L/B`:

* the norm (equivalently, the `X`-adic valuation) extends uniquely to `L`
  (via the spectral norm);
* `L` is complete;
* the value group of `L` is `q^{(1/e)ℤ}` for some `e ∣ [L:B]`;
* when `K` is algebraically closed, the residue field of `L` is `K` and the
  extension is totally ramified (`e = [L:B]`).

This is Lemma `lem:ext-valuation` of the blueprint (Kedlaya 2001a, §3).
-/

@[expose] public section

namespace TrustworthyKedlaya.Ext

open LaurentSeries Valuation
open scoped WithZero

variable (K : Type*) [Field K]

/-- The `X`-adic valuation on `K⸨X⸩` is rank-one discrete. -/
instance : (Valued.v : Valuation K⸨X⸩ ℤᵐ⁰).IsRankOneDiscrete where
  exists_generator_lt_one' := by
    refine ⟨Units.mk0 (WithZero.exp (-1)) WithZero.exp_ne_zero, ?_, ?_⟩
    · have htop : (MonoidWithZeroHom.ofClass (Valued.v : Valuation K⸨X⸩ ℤᵐ⁰)).valueGroup = ⊤ := by
        rw [Subgroup.eq_top_iff']
        intro u
        exact MonoidWithZeroHom.mem_valueGroup _ (LaurentSeries.valuation_surjective K u.1)
      rw [htop, Subgroup.eq_top_iff']
      intro u
      rw [Subgroup.mem_zpowers_iff]
      refine ⟨-WithZero.log u.1, Units.ext ?_⟩
      rw [Units.val_zpow_eq_zpow_val, Units.val_mk0, ← WithZero.exp_zsmul, smul_neg, smul_eq_mul,
        mul_one, neg_neg, WithZero.exp_log u.ne_zero]
    · rw [← Units.val_lt_val, Units.val_mk0, Units.val_one, ← WithZero.exp_zero]
      exact WithZero.exp_lt_exp.mpr (by norm_num)

/-- A rank-one structure on the `X`-adic valuation of `K⸨X⸩` (with normalization
`‖X‖ = 1/2`; only the induced topology matters). -/
noncomputable instance : (Valued.v : Valuation K⸨X⸩ ℤᵐ⁰).RankOne :=
  IsRankOneDiscrete.rankOne _ one_lt_two

open scoped Valued

section BaseField

variable {K}

/-- Two Laurent series with the same valuation have the same norm. -/
theorem norm_eq_of_valuation_eq {f g : K⸨X⸩} (h : Valued.v f = Valued.v g) : ‖f‖ = ‖g‖ :=
  le_antisymm (Valued.toNormedField.norm_le_iff.mpr h.le)
    (Valued.toNormedField.norm_le_iff.mpr h.ge)

/-- The norm of `X` in `K⸨X⸩` is strictly between `0` and `1`. -/
theorem norm_X_pos : 0 < ‖(HahnSeries.single 1 1 : K⸨X⸩)‖ := by
  rw [norm_pos_iff]
  exact HahnSeries.single_ne_zero one_ne_zero

theorem norm_X_lt_one : ‖(HahnSeries.single 1 1 : K⸨X⸩)‖ < 1 := by
  rw [Valued.toNormedField.norm_lt_one_iff, LaurentSeries.valuation_single_zpow,
    ← WithZero.exp_zero]
  exact WithZero.exp_lt_exp.mpr (by norm_num)

/-- The value group of `K⸨X⸩` is generated by the norm of `X`: every nonzero
Laurent series has norm an integer power of `‖X‖`. -/
theorem exists_norm_eq_zpow (f : K⸨X⸩) (hf : f ≠ 0) :
    ∃ m : ℤ, ‖f‖ = ‖(HahnSeries.single 1 1 : K⸨X⸩)‖ ^ m := by
  have hv : Valued.v f ≠ (0 : ℤᵐ⁰) := (Valuation.ne_zero_iff _).mpr hf
  refine ⟨-WithZero.log (Valued.v f), ?_⟩
  rw [← norm_zpow]
  refine norm_eq_of_valuation_eq ?_
  rw [map_zpow₀, LaurentSeries.valuation_single_zpow, ← WithZero.exp_zsmul]
  rw [← WithZero.exp_log hv]
  congr 1
  simp

end BaseField

section Extension

variable {K} {L : Type*} [Field L] [Algebra K⸨X⸩ L] [Module.Finite K⸨X⸩ L]

/-- **Uniqueness of the extended absolute value**: any absolute value on a finite
extension `L` of `K⸨X⸩` restricting to the `X`-adic norm on `K⸨X⸩` coincides with
the spectral norm. -/
theorem absoluteValue_eq_spectralNorm (f : AbsoluteValue L ℝ)
    (hf : ∀ b : K⸨X⸩, f (algebraMap K⸨X⸩ L b) = ‖b‖) (x : L) :
    f x = spectralNorm K⸨X⸩ L x :=
  spectralNorm_unique_field_norm_ext hf x

/-- The `[L : K⸨X⸩]`-th power of the spectral norm of a nonzero element of a finite
extension of `K⸨X⸩` lies in the value group `‖X‖^ℤ` of the base field. -/
theorem spectralNorm_pow_finrank_eq_zpow (x : L) (hx : x ≠ 0) :
    ∃ m : ℤ, spectralNorm K⸨X⸩ L x ^ Module.finrank K⸨X⸩ L =
      ‖(HahnSeries.single 1 1 : K⸨X⸩)‖ ^ m := by
  have hint : IsIntegral K⸨X⸩ x := Algebra.IsIntegral.isIntegral x
  have hn_pos : 0 < (minpoly K⸨X⸩ x).natDegree := minpoly.natDegree_pos hint
  obtain ⟨k, hk⟩ : (minpoly K⸨X⸩ x).natDegree ∣ Module.finrank K⸨X⸩ L :=
    minpoly.degree_dvd hint
  have ha0 : (minpoly K⸨X⸩ x).coeff 0 ≠ 0 := minpoly.coeff_zero_ne_zero hint hx
  obtain ⟨m₀, hm₀⟩ := exists_norm_eq_zpow _ ha0
  refine ⟨m₀ * k, ?_⟩
  rw [spectralNorm.spectralNorm_eq_norm_coeff_zero_rpow, hk, ← Real.rpow_natCast
    (‖(minpoly K⸨X⸩ x).coeff 0‖ ^ (1 / ((minpoly K⸨X⸩ x).natDegree : ℝ))) _,
    ← Real.rpow_mul (norm_nonneg _)]
  have hexp : 1 / ((minpoly K⸨X⸩ x).natDegree : ℝ) *
      (((minpoly K⸨X⸩ x).natDegree * k : ℕ) : ℝ) = (k : ℝ) := by
    have : ((minpoly K⸨X⸩ x).natDegree : ℝ) ≠ 0 := by exact_mod_cast hn_pos.ne'
    push_cast
    field_simp
  rw [hexp, Real.rpow_natCast, hm₀, ← zpow_natCast, ← zpow_mul]

/-- A finite extension of `K⸨X⸩` is a complete space under (the metric of) the
spectral norm. -/
theorem completeSpace_of_finite : @CompleteSpace L (spectralNorm.uniformSpace K⸨X⸩ L) :=
  spectralNorm.completeSpace K⸨X⸩ L

/-- **The value group of a finite extension of `K⸨X⸩` is discrete**: there are `e ∣ [L : K⸨X⸩]`
and a uniformizing element `π` with `‖π‖^e = ‖X‖` such that every nonzero element of `L` has
spectral norm an integer power of `‖π‖`. In particular the value group of `L` is `‖X‖^{(1/e)ℤ}`
and the ramification index divides the degree. -/
theorem exists_spectralNorm_uniformizer :
    ∃ (e : ℕ) (π : L), 0 < e ∧ e ∣ Module.finrank K⸨X⸩ L ∧
      spectralNorm K⸨X⸩ L π ^ e = ‖(HahnSeries.single 1 1 : K⸨X⸩)‖ ∧
      ∀ x : L, x ≠ 0 → ∃ m : ℤ, spectralNorm K⸨X⸩ L x = spectralNorm K⸨X⸩ L π ^ m := by
  let _ : NormedField L := spectralNorm.normedField K⸨X⸩ L
  have hnorm : ∀ y : L, ‖y‖ = spectralNorm K⸨X⸩ L y := fun _ => rfl
  set q : ℝ := ‖(HahnSeries.single 1 1 : K⸨X⸩)‖ with hq
  have hq0 : 0 < q := norm_X_pos
  have hq1 : q < 1 := norm_X_lt_one
  set d : ℕ := Module.finrank K⸨X⸩ L with hd
  have hd0 : 0 < d := Module.finrank_pos
  -- the group of achieved exponents: `m ∈ H` iff some nonzero `x` has `‖x‖^d = q^m`
  set H : AddSubgroup ℤ :=
    { carrier := {m : ℤ | ∃ x : L, x ≠ 0 ∧ ‖x‖ ^ d = q ^ m}
      zero_mem' := ⟨1, one_ne_zero, by simp⟩
      add_mem' := by
        rintro a b ⟨x, hx, hxa⟩ ⟨y, hy, hyb⟩
        exact ⟨x * y, mul_ne_zero hx hy, by
          rw [norm_mul, mul_pow, hxa, hyb, ← zpow_add₀ hq0.ne']⟩
      neg_mem' := by
        rintro a ⟨x, hx, hxa⟩
        exact ⟨x⁻¹, inv_ne_zero hx, by
          rw [norm_inv, inv_pow, hxa, ← zpow_neg]⟩ } with hH
  have hdH : (d : ℤ) ∈ H := by
    refine ⟨algebraMap K⸨X⸩ L (HahnSeries.single 1 1), ?_, ?_⟩
    · simp
    · rw [hnorm, spectralNorm_extends, ← hq, zpow_natCast]
  obtain ⟨g, hg⟩ := Int.subgroup_cyclic H
  -- normalize the generator to be positive
  have hg_mem : g ∈ H := hg ▸ AddSubgroup.mem_closure_singleton.mpr ⟨1, one_smul _ _⟩
  have hgd : g ∣ (d : ℤ) := by
    obtain ⟨k, hk⟩ := AddSubgroup.mem_closure_singleton.mp (hg ▸ hdH)
    exact ⟨k, by rw [← hk, smul_eq_mul, mul_comm]⟩
  have hg0 : g ≠ 0 := by
    rintro rfl
    exact hd0.ne' (by exact_mod_cast (zero_dvd_iff.mp hgd))
  have hdvd_all : ∀ m ∈ H, g ∣ m := by
    intro m hm
    obtain ⟨k, hk⟩ := AddSubgroup.mem_closure_singleton.mp (hg ▸ hm)
    exact ⟨k, by rw [← hk, smul_eq_mul, mul_comm]⟩
  -- pass to the positive generator `gn = |g|`
  set gn : ℕ := g.natAbs with hgn
  have hgn0 : 0 < gn := Int.natAbs_pos.mpr hg0
  have hgn_mem : (gn : ℤ) ∈ H := by
    rcases Int.natAbs_eq g with h | h
    · exact h ▸ hg_mem
    · have hng : ((gn : ℤ)) = -g := by omega
      rw [hng]
      exact H.neg_mem hg_mem
  have hgn_dvd : ∀ m ∈ H, (gn : ℤ) ∣ m := fun m hm =>
    (Int.natAbs_dvd.mpr (hdvd_all m hm))
  obtain ⟨e, he⟩ : gn ∣ d := Int.ofNat_dvd.mp (Int.natAbs_dvd.mpr hgd)
  have he0 : 0 < e := by
    rcases Nat.eq_zero_or_pos e with rfl | h
    · exact absurd (by simpa using he) hd0.ne'
    · exact h
  obtain ⟨π, hπ0, hπ⟩ := hgn_mem
  have hπ_pos : 0 < ‖π‖ := norm_pos_iff.mpr hπ0
  refine ⟨e, π, he0, ⟨gn, by rw [he, mul_comm]⟩, ?_, ?_⟩
  · -- `‖π‖ ^ e = q`, by taking `gn`-th roots of `‖π‖ ^ d = q ^ gn`
    rw [← hnorm]
    refine (pow_left_strictMonoOn₀ (M₀ := ℝ) (n := gn) hgn0.ne').injOn
      (pow_nonneg hπ_pos.le _) hq0.le ?_
    rw [← pow_mul, mul_comm e gn, ← he, hπ, zpow_natCast]
  · -- every nonzero `x` has norm a power of `‖π‖`
    intro x hx
    obtain ⟨m, hm⟩ := spectralNorm_pow_finrank_eq_zpow (K := K) x hx
    rw [← hnorm, ← hnorm] at *
    have hmH : m ∈ H := ⟨x, hx, hm⟩
    obtain ⟨j, hj⟩ := hgn_dvd m hmH
    refine ⟨j, ?_⟩
    have hx_pos : 0 < ‖x‖ := norm_pos_iff.mpr hx
    refine (pow_left_strictMonoOn₀ (M₀ := ℝ) (n := d) hd0.ne').injOn
      hx_pos.le (zpow_nonneg hπ_pos.le _) ?_
    rw [hm, hj, zpow_mul, ← hπ, ← zpow_natCast ‖π‖ d, ← zpow_mul,
      ← zpow_natCast (‖π‖ ^ j) d, ← zpow_mul, mul_comm]

end Extension

section Residue

variable {K}

/-- Any Laurent series of norm at most `1` is congruent to its constant coefficient
modulo the maximal ideal: subtracting it leaves norm strictly less than `1`. -/
theorem norm_sub_C_coeff_zero_lt_one {b : K⸨X⸩} (hb : ‖b‖ ≤ 1) :
    ‖b - HahnSeries.C (b.coeff 0)‖ < 1 := by
  have hb' : Valued.v b ≤ WithZero.exp (-(0 : ℤ)) := by
    rw [neg_zero, WithZero.exp_zero]
    exact Valued.toNormedField.norm_le_one_iff.mp hb
  have hcoeff := (LaurentSeries.valuation_le_iff_coeff_lt_eq_zero K).mp hb'
  rw [Valued.toNormedField.norm_lt_one_iff]
  refine lt_of_le_of_lt ((LaurentSeries.valuation_le_iff_coeff_lt_eq_zero K (D := 1)).mpr
    fun n hn => ?_) ?_
  · rcases lt_or_eq_of_le (show n ≤ 0 by omega) with hn0 | hn0
    · rw [HahnSeries.coeff_sub, hcoeff n hn0, HahnSeries.C_apply,
        HahnSeries.coeff_single_of_ne hn0.ne, sub_zero]
    · rw [HahnSeries.coeff_sub, hn0, HahnSeries.C_apply, HahnSeries.coeff_single_same, sub_self]
  · rw [← WithZero.exp_zero]
    exact WithZero.exp_lt_exp.mpr (by norm_num)

variable {L : Type*} [Field L] [Algebra K⸨X⸩ L] [Module.Finite K⸨X⸩ L]

/-- If `x` has spectral norm at most `1`, every coefficient of its minimal polynomial
over `K⸨X⸩` has norm at most `1`. -/
theorem norm_minpoly_coeff_le_one {x : L} (hx : spectralNorm K⸨X⸩ L x ≤ 1) (i : ℕ) :
    ‖(minpoly K⸨X⸩ x).coeff i‖ ≤ 1 := by
  rcases lt_trichotomy i (minpoly K⸨X⸩ x).natDegree with hi | hi | hi
  · -- the spectral-value term at `i` is bounded by the spectral norm
    have hterm := le_ciSup (spectralValueTerms_bddAbove (minpoly K⸨X⸩ x)) i
    rw [spectralValueTerms_of_lt_natDegree _ hi] at hterm
    have h1 : ‖(minpoly K⸨X⸩ x).coeff i‖ ^
        (1 / ((minpoly K⸨X⸩ x).natDegree - i : ℝ)) ≤ 1 := hterm.trans hx
    by_contra hgt
    push Not at hgt
    have hpow : (1 : ℝ) < ‖(minpoly K⸨X⸩ x).coeff i‖ ^
        (1 / ((minpoly K⸨X⸩ x).natDegree - i : ℝ)) := by
      refine Real.one_lt_rpow_iff_of_pos (lt_trans one_pos hgt) |>.mpr (Or.inl ⟨hgt, ?_⟩)
      have : (0 : ℝ) < ((minpoly K⸨X⸩ x).natDegree - i : ℝ) := by
        rw [sub_pos]
        exact_mod_cast hi
      positivity
    exact absurd h1 (not_le.mpr hpow)
  · rw [hi, (minpoly.monic (Algebra.IsIntegral.isIntegral x)).coeff_natDegree, norm_one]
  · rw [Polynomial.coeff_eq_zero_of_natDegree_lt hi, norm_zero]
    exact zero_le_one

/-- **The residue field of a finite extension of `K⸨X⸩` is `K`** when `K` is algebraically
closed: any element of the closed unit ball of `L` is congruent to a constant `c : K`
modulo the open unit ball. -/
theorem exists_residue [IsAlgClosed K] (x : L) (hx : spectralNorm K⸨X⸩ L x ≤ 1) :
    ∃ c : K, spectralNorm K⸨X⸩ L (x - algebraMap K⸨X⸩ L (HahnSeries.C c)) < 1 := by
  let _ : NormedField L := spectralNorm.normedField K⸨X⸩ L
  have hnorm : ∀ y : L, ‖y‖ = spectralNorm K⸨X⸩ L y := fun _ => rfl
  have _ : IsUltrametricDist L :=
    IsUltrametricDist.isUltrametricDist_of_forall_norm_add_le_max_norm
      (isNonarchimedean_spectralNorm (K := K⸨X⸩) (L := L))
  let _ : Algebra K L := ((algebraMap K⸨X⸩ L).comp (algebraMap K K⸨X⸩)).toAlgebra
  have halgC : ∀ c : K, algebraMap K K⸨X⸩ c = HahnSeries.C c := fun c => by
    rw [HahnSeries.algebraMap_apply']
    simp [PowerSeries.algebraMap_eq]
  have hint : IsIntegral K⸨X⸩ x := Algebra.IsIntegral.isIntegral x
  set f : Polynomial K⸨X⸩ := minpoly K⸨X⸩ x with hfdef
  have hmonic : f.Monic := minpoly.monic hint
  set n := f.natDegree with hn
  -- the reduction of `f` modulo the maximal ideal of `K⸨X⸩`
  set pbar : Polynomial K := ∑ i ∈ Finset.range (n + 1),
    Polynomial.C ((f.coeff i).coeff 0) * Polynomial.X ^ i with hpbar
  have hpbar_coeff : ∀ j, pbar.coeff j =
      if j ∈ Finset.range (n + 1) then (f.coeff j).coeff 0 else 0 := by
    intro j
    rw [hpbar, Polynomial.finsetSum_coeff]
    simp only [Polynomial.coeff_C_mul_X_pow]
    exact Finset.sum_ite_eq (Finset.range (n + 1)) j fun i => (f.coeff i).coeff 0
  have hpbar_deg : pbar.natDegree ≤ n := by
    rw [hpbar]
    refine Polynomial.natDegree_sum_le_of_forall_le _ _ fun i hi => ?_
    exact (Polynomial.natDegree_C_mul_le _ _).trans
      ((Polynomial.natDegree_X_pow_le _).trans (by
        have := Finset.mem_range.mp hi
        omega))
  have hpbar_monic : pbar.Monic := by
    refine Polynomial.monic_of_natDegree_le_of_coeff_eq_one n hpbar_deg ?_
    rw [hpbar_coeff, if_pos (Finset.mem_range.mpr (by omega)), hmonic.coeff_natDegree,
      HahnSeries.coeff_one, if_pos rfl]
  -- the lift of `pbar` back to `K⸨X⸩` differs from `f` by coefficients of norm `< 1`
  set g : Polynomial K⸨X⸩ := pbar.map (algebraMap K K⸨X⸩) with hg
  have hfg_coeff : ∀ j, ‖(f - g).coeff j‖ < 1 := by
    intro j
    rw [Polynomial.coeff_sub, hg, Polynomial.coeff_map, halgC]
    by_cases hj : j ∈ Finset.range (n + 1)
    · rw [hpbar_coeff, if_pos hj]
      exact norm_sub_C_coeff_zero_lt_one (norm_minpoly_coeff_le_one hx j)
    · rw [hpbar_coeff, if_neg hj, Polynomial.coeff_eq_zero_of_natDegree_lt
        (lt_of_le_of_lt (le_refl n) (by
          have := Finset.mem_range.not.mp hj
          omega)), map_zero, sub_zero, norm_zero]
      exact one_pos
  -- evaluate: `‖g(x)‖ = ‖(g - f)(x)‖ < 1` since `f(x) = 0`
  have hdeg : (f - g).natDegree < n + 1 := by
    refine lt_of_le_of_lt (Polynomial.natDegree_sub_le f g) ?_
    have hgdeg : g.natDegree ≤ n := (Polynomial.natDegree_map_le).trans hpbar_deg
    omega
  have hlt : ‖Polynomial.aeval x (f - g)‖ < 1 := by
    rw [Polynomial.aeval_eq_sum_range' hdeg x]
    obtain ⟨i, _, hi_le⟩ := IsUltrametricDist.exists_norm_finsetSum_le_of_nonempty
      Finset.nonempty_range_add_one (fun i => (f - g).coeff i • x ^ i)
    refine lt_of_le_of_lt hi_le ?_
    rw [Algebra.smul_def, norm_mul, hnorm (algebraMap K⸨X⸩ L _), spectralNorm_extends]
    calc ‖(f - g).coeff i‖ * ‖x ^ i‖
        ≤ ‖(f - g).coeff i‖ * 1 := by
          refine mul_le_mul_of_nonneg_left ?_ (norm_nonneg _)
          rw [norm_pow]
          exact pow_le_one₀ (norm_nonneg _) hx
      _ < 1 := by rw [mul_one]; exact hfg_coeff i
  have hgval : ‖Polynomial.aeval x g‖ < 1 := by
    have hzero : Polynomial.aeval x f = 0 := minpoly.aeval K⸨X⸩ x
    have : Polynomial.aeval x g = -(Polynomial.aeval x (f - g)) := by
      rw [_root_.map_sub, hzero, zero_sub, neg_neg]
    rw [this, norm_neg]
    exact hlt
  -- factor `pbar` into linear factors over the algebraically closed `K`
  have hsplits : pbar.Splits := IsAlgClosed.splits pbar
  have hprod : Polynomial.aeval x pbar =
      (pbar.roots.map fun a => x - algebraMap K L a).prod := by
    conv_lhs => rw [hsplits.eq_prod_roots_of_monic hpbar_monic]
    rw [map_multiset_prod, Multiset.map_map]
    refine congr_arg _ (Multiset.map_congr rfl fun a _ => ?_)
    simp
  have hnorm_prod : ((pbar.roots.map fun a => x - algebraMap K L a).map
      fun y => ‖y‖₊).prod < 1 := by
    have haeval_map : Polynomial.aeval x g = Polynomial.aeval (R := K) x pbar := by
      rw [hg, Polynomial.aeval_def, Polynomial.eval₂_map, Polynomial.aeval_def]
      rfl
    have hval : ‖(pbar.roots.map fun a => x - algebraMap K L a).prod‖₊ < 1 := by
      rw [← NNReal.coe_lt_coe, coe_nnnorm, NNReal.coe_one, ← hprod, ← haeval_map]
      exact hgval
    calc ((pbar.roots.map fun a => x - algebraMap K L a).map fun y => ‖y‖₊).prod
        = ‖(pbar.roots.map fun a => x - algebraMap K L a).prod‖₊ :=
          (map_multiset_prod (nnnormHom : L →*₀ NNReal) _).symm
      _ < 1 := hval
  -- some factor must have norm `< 1`
  by_contra hcon
  push Not at hcon
  refine absurd hnorm_prod (not_lt.mpr (Multiset.one_le_prod_of_one_le fun r hr => ?_))
  rw [Multiset.map_map] at hr
  obtain ⟨a, _, rfl⟩ := Multiset.mem_map.mp hr
  have hge := hcon a
  rw [← hnorm] at hge
  have hbridge : algebraMap K⸨X⸩ L (HahnSeries.C a) = algebraMap K L a := by
    rw [← halgC a]
    rfl
  rw [hbridge, ← not_lt] at hge
  rw [Function.comp_apply, ← NNReal.coe_le_coe, NNReal.coe_one, coe_nnnorm]
  exact not_lt.mp hge

/-- **The powers of a uniformizer span**: if `‖π‖ ^ e = ‖X‖` and every nonzero element
of `L` has spectral norm an integer power of `‖π‖`, then `1, π, …, π^{e-1}` span `L`
over `K⸨X⸩` (by successive approximation against this span, which is closed by
finite-dimensionality and dense by geometric decay). -/
theorem span_pow_eq_top_of_spectralNorm_pow_eq [IsAlgClosed K] {π : L} {e : ℕ} (he0 : 0 < e)
    (hπe : spectralNorm K⸨X⸩ L π ^ e = ‖(HahnSeries.single 1 1 : K⸨X⸩)‖)
    (hall : ∀ x : L, x ≠ 0 → ∃ m : ℤ, spectralNorm K⸨X⸩ L x = spectralNorm K⸨X⸩ L π ^ m) :
    Submodule.span K⸨X⸩ (Set.range fun i : Fin e => π ^ (i : ℕ)) = ⊤ := by
  let _ : NormedField L := spectralNorm.normedField K⸨X⸩ L
  have hnorm : ∀ y : L, ‖y‖ = spectralNorm K⸨X⸩ L y := fun _ => rfl
  let _ : NormedAlgebra K⸨X⸩ L := spectralNorm.normedAlgebra K⸨X⸩ L
  set q : ℝ := ‖(HahnSeries.single 1 1 : K⸨X⸩)‖ with hq
  have hq0 : 0 < q := norm_X_pos
  have hq1 : q < 1 := norm_X_lt_one
  rw [← hnorm π] at hπe hall
  have hπ0 : 0 < ‖π‖ := by
    rcases (norm_nonneg π).lt_or_eq with h | h
    · exact h
    · exact absurd (hπe.symm.trans (by rw [← h, zero_pow he0.ne'])) hq0.ne'
  have hπ1 : ‖π‖ < 1 := by
    by_contra hge
    push Not at hge
    exact absurd hπe (by
      intro hcon
      exact absurd (hcon ▸ one_le_pow₀ hge) (not_le.mpr hq1))
  -- the candidate spanning set
  set M : Submodule K⸨X⸩ L :=
    Submodule.span K⸨X⸩ (Set.range fun i : Fin e => π ^ (i : ℕ)) with hM
  -- one-step approximation: any element can be reduced by a factor `‖π‖` using `M`
  have step : ∀ x : L, ∃ m ∈ M, ‖x - m‖ ≤ ‖π‖ * ‖x‖ := by
    intro x
    rcases eq_or_ne x 0 with rfl | hx
    · exact ⟨0, M.zero_mem, by simp⟩
    obtain ⟨k, hk⟩ := hall x hx
    rw [← hnorm x] at hk
    have hi0 : 0 ≤ k % e := Int.emod_nonneg k (by exact_mod_cast he0.ne')
    have hie : k % e < e := Int.emod_lt_of_pos k (by exact_mod_cast he0)
    set inat : ℕ := (k % e).toNat with hinat
    set b : K⸨X⸩ := (HahnSeries.single 1 1 : K⸨X⸩) ^ (k / e) with hb
    have hb0 : b ≠ 0 := zpow_ne_zero _ (HahnSeries.single_ne_zero one_ne_zero)
    set τ : L := algebraMap K⸨X⸩ L b * π ^ inat with hτ
    have hτnorm : ‖τ‖ = ‖x‖ := by
      rw [hτ, norm_mul, hnorm (algebraMap K⸨X⸩ L b), spectralNorm_extends, hb, norm_zpow,
        norm_pow, hk]
      rw [← hq, ← hπe, ← zpow_natCast ‖π‖ e, ← zpow_natCast ‖π‖ inat, ← zpow_mul,
        ← zpow_add₀ hπ0.ne']
      congr 1
      rw [hinat, Int.toNat_of_nonneg hi0, mul_comm ((e : ℤ)) (k / (e : ℤ))]
      exact Int.ediv_mul_add_emod k e
    have hτ0 : τ ≠ 0 := by
      intro hcon
      rw [hcon, norm_zero] at hτnorm
      exact hx (norm_eq_zero.mp hτnorm.symm)
    obtain ⟨c, hc⟩ := exists_residue (x / τ) (by
      rw [← hnorm, norm_div, hτnorm, div_self (norm_pos_iff.mpr hx).ne'])
    rw [← hnorm] at hc
    refine ⟨algebraMap K⸨X⸩ L (HahnSeries.C c) * τ, ?_, ?_⟩
    · rw [hτ, ← mul_assoc, ← _root_.map_mul]
      rw [← Algebra.smul_def]
      refine M.smul_mem _ (Submodule.subset_span ?_)
      exact ⟨⟨inat, by omega⟩, rfl⟩
    · have hfactor : x - algebraMap K⸨X⸩ L (HahnSeries.C c) * τ =
          τ * (x / τ - algebraMap K⸨X⸩ L (HahnSeries.C c)) := by
        field_simp
      rw [hfactor, norm_mul, hτnorm, mul_comm ‖x‖ _]
      refine mul_le_mul_of_nonneg_right ?_ (norm_nonneg x)
      -- discreteness: a norm `< 1` is at most `‖π‖`
      rcases eq_or_ne (x / τ - algebraMap K⸨X⸩ L (HahnSeries.C c)) 0 with hy | hy
      · rw [hy, norm_zero]
        exact hπ0.le
      · obtain ⟨j, hj⟩ := hall _ hy
        rw [← hnorm] at hj
        rw [hj] at hc ⊢
        have hj1 : 1 ≤ j := by
          by_contra hjle
          push Not at hjle
          have : (1 : ℝ) ≤ ‖π‖ ^ j := by
            rcases Int.lt_iff_add_one_le.mp hjle |>.lt_or_eq with h | h
            · calc (1 : ℝ) = ‖π‖ ^ (0 : ℤ) := (zpow_zero _).symm
                _ ≤ ‖π‖ ^ j := by
                  refine zpow_le_zpow_right_of_le_one₀ hπ0 hπ1.le ?_
                  omega
            · rw [show j = 0 by omega, zpow_zero]
          exact absurd hc (not_lt.mpr this)
        calc ‖π‖ ^ j ≤ ‖π‖ ^ (1 : ℤ) := zpow_le_zpow_right_of_le_one₀ hπ0 hπ1.le hj1
          _ = ‖π‖ := zpow_one _
  -- iterate the reduction: `M` approximates every element geometrically
  have iterate : ∀ (j : ℕ) (x : L), ∃ m ∈ M, ‖x - m‖ ≤ ‖π‖ ^ j * ‖x‖ := by
    intro j
    induction j with
    | zero => exact fun x => ⟨0, M.zero_mem, by simp⟩
    | succ j ih =>
      intro x
      obtain ⟨m, hm, hbound⟩ := ih x
      obtain ⟨m', hm', hbound'⟩ := step (x - m)
      refine ⟨m + m', M.add_mem hm hm', ?_⟩
      have hsub : x - (m + m') = x - m - m' := by ring
      rw [hsub]
      calc ‖x - m - m'‖ ≤ ‖π‖ * ‖x - m‖ := hbound'
        _ ≤ ‖π‖ * (‖π‖ ^ j * ‖x‖) := mul_le_mul_of_nonneg_left hbound hπ0.le
        _ = ‖π‖ ^ (j + 1) * ‖x‖ := by ring
  -- `M` is a closed subspace containing a dense set, hence everything
  have _ : FiniteDimensional K⸨X⸩ M :=
    FiniteDimensional.span_of_finite _ (Set.finite_range _)
  have hM_closed : IsClosed (M : Set L) := Submodule.closed_of_finiteDimensional M
  have hM_top : M = ⊤ := by
    rw [Submodule.eq_top_iff']
    intro x
    have hx_closure : x ∈ closure (M : Set L) := by
      rw [Metric.mem_closure_iff]
      intro ε hε
      obtain ⟨j, hj⟩ := exists_pow_lt_of_lt_one
        (div_pos hε (lt_of_le_of_lt (norm_nonneg x) (lt_add_one _))) hπ1
      obtain ⟨m, hm, hbound⟩ := iterate j x
      refine ⟨m, hm, ?_⟩
      rw [dist_eq_norm]
      have hx1 : (0 : ℝ) < ‖x‖ + 1 := lt_of_le_of_lt (norm_nonneg x) (lt_add_one _)
      calc ‖x - m‖ ≤ ‖π‖ ^ j * ‖x‖ := hbound
        _ ≤ ‖π‖ ^ j * (‖x‖ + 1) :=
          mul_le_mul_of_nonneg_left (by linarith) (pow_nonneg hπ0.le j)
        _ < ε / (‖x‖ + 1) * (‖x‖ + 1) := mul_lt_mul_of_pos_right hj hx1
        _ = ε := div_mul_cancel₀ ε hx1.ne'
    rwa [hM_closed.closure_eq] at hx_closure
  exact hM_top

/-- **Finite extensions of `K⸨X⸩` are totally ramified when `K` is algebraically closed**:
the ramification index equals the degree, i.e. there is `π : L` with
`‖π‖ ^ [L : K⸨X⸩] = ‖X‖` whose powers give the norms of all nonzero elements.
(In particular the `e` of `exists_spectralNorm_uniformizer` is exactly `[L : K⸨X⸩]`;
this subsumes the Galois case of the blueprint statement.) -/
theorem exists_spectralNorm_uniformizer_pow_finrank [IsAlgClosed K] :
    ∃ π : L, spectralNorm K⸨X⸩ L π ^ Module.finrank K⸨X⸩ L =
        ‖(HahnSeries.single 1 1 : K⸨X⸩)‖ ∧
      ∀ x : L, x ≠ 0 → ∃ m : ℤ, spectralNorm K⸨X⸩ L x = spectralNorm K⸨X⸩ L π ^ m := by
  obtain ⟨e, π, he0, hed, hπe, hall⟩ := exists_spectralNorm_uniformizer (K := K) (L := L)
  suffices heq : e = Module.finrank K⸨X⸩ L by
    refine ⟨π, ?_, hall⟩
    rw [← heq]
    exact hπe
  have hspan := span_pow_eq_top_of_spectralNorm_pow_eq he0 hπe hall
  have hle : Module.finrank K⸨X⸩ L ≤ e := by
    have := finrank_le_of_span_eq_top hspan
    simpa using this
  exact le_antisymm (Nat.le_of_dvd Module.finrank_pos hed) hle

end Residue

end TrustworthyKedlaya.Ext
