/-
Copyright (c) 2026 Yijun Yuan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yijun Yuan
-/
module

public import TrustworthyKedlaya.ArtinSchreierGalois
public import TrustworthyKedlaya.Galois
public import TrustworthyKedlaya.PGroupGalois
public import TrustworthyKedlaya.TameKummer

/-!
# Kedlaya 2001a, Lemma 3: the Artin–Schreier tower

Two results:

* `TrustworthyKedlaya.exists_artinSchreier_chain` — the wild part: if `E/N` is a finite
  Galois extension in characteristic `p` whose Galois group is a `p`-group (`N` an
  intermediate field of an ambient extension `E/F`), then iterating the single tower
  step (`exists_intermediateField_isGalois_of_isPGroup`, by induction on the degree)
  and the Artin–Schreier generator (`exists_artinSchreier_generator`) yields a chain
  `N = M₀ ≤ M₁ ≤ ⋯ ≤ M_r = ⊤` of intermediate fields of `E/F` in which each step is
  generated by an Artin–Schreier element: `M_{i+1} = M_i(θ_i)` with `θ_i^p - θ_i ∈ M_i`.

* `TrustworthyKedlaya.Ext.exists_artinSchreier_tower` — the assembly (Kedlaya 2001a,
  Lemma 3, for Galois extensions): every finite Galois extension `L` of `B = K⸨X⸩`
  (`K` algebraically closed of characteristic `p`) carries such a chain starting from
  `M₀ = B(u)` with `u^n = X` for some `n` prime to `p`.  The wild inertia subgroup
  `P = ker(tameCharacter)` is a normal `p`-Sylow subgroup with cyclic prime-to-`p`
  quotient; its fixed field is `B(u)` by `lem:tame-kummer`, and the chain above it
  comes from the wild part.

This is `prop:gal-tower` of the blueprint (Kedlaya 2001a, proof of Lemma 3).
-/

@[expose] public section

namespace TrustworthyKedlaya

open IntermediateField

/-- **Artin–Schreier chains for `p`-group Galois extensions**: if `E/N` is a finite Galois
extension in characteristic `p` whose Galois group is a `p`-group, with `N` an
intermediate field of some ambient extension `E/F`, then there is a chain
`N = M₀ ≤ M₁ ≤ ⋯ ≤ M_r = ⊤` of intermediate fields of `E/F` such that each step is
generated by an Artin–Schreier element: `M_{i+1} = M_i(θ_i)` with `θ_i^p - θ_i ∈ M_i`. -/
theorem exists_artinSchreier_chain (p : ℕ) [Fact p.Prime] {F E : Type*} [Field F] [Field E]
    [Algebra F E] [CharP F p] [FiniteDimensional F E]
    (N : IntermediateField F E) (hgal : IsGalois N E) (hG : IsPGroup p (E ≃ₐ[N] E)) :
    ∃ (r : ℕ) (M : Fin (r + 1) → IntermediateField F E),
      M 0 = N ∧ M (Fin.last r) = ⊤ ∧
      ∀ i : Fin r, ∃ θ : E, θ ^ p - θ ∈ M i.castSucc ∧
        M i.succ = M i.castSucc ⊔ IntermediateField.adjoin F {θ} := by
  induction hd : Module.finrank N E using Nat.strong_induction_on generalizing N with
  | _ d IH =>
  subst hd
  rcases eq_or_ne (Module.finrank N E) 1 with hd1 | hd1
  · -- trivial chain: `N = ⊤`
    have hNtop : N = ⊤ := IntermediateField.finrank_eq_one_iff_eq_top.mp hd1
    exact ⟨0, fun _ => N, rfl, hNtop, fun i => i.elim0⟩
  · have := hgal
    have : CharP N p := charP_of_injective_algebraMap (algebraMap F N).injective p
    have hlt : 1 < Module.finrank N E :=
      lt_of_le_of_ne Module.finrank_pos hd1.symm
    -- one degree-`p` step
    obtain ⟨M', hM'gal, hM'rank, hM'p⟩ :=
      exists_intermediateField_isGalois_of_isPGroup p hG hlt
    have := hM'gal
    set N' : IntermediateField F E := M'.restrictScalars F with hN'
    -- the new base `N'` inherits the hypotheses
    have hgal' : IsGalois N' E := IsGalois.tower_top_intermediateField M'
    have hG' : IsPGroup p (E ≃ₐ[N'] E) := hM'p
    -- the degree drops
    have hmul : Module.finrank N M' * Module.finrank M' E = Module.finrank N E :=
      Module.finrank_mul_finrank N M' E
    have hM'E_pos : 0 < Module.finrank M' E := Module.finrank_pos
    have hdlt : Module.finrank N' E < Module.finrank N E := by
      have hp2 : 2 ≤ p := (Fact.out : p.Prime).two_le
      have : Module.finrank N' E = Module.finrank M' E := rfl
      rw [this, ← hmul, hM'rank]
      calc Module.finrank M' E < 2 * Module.finrank M' E := by omega
        _ ≤ p * Module.finrank M' E := Nat.mul_le_mul_right _ hp2
    -- the chain above `N'`, by induction
    obtain ⟨r, M, hM0, hMlast, hMstep⟩ :=
      IH (Module.finrank N' E) hdlt N' hgal' hG' rfl
    -- the Artin–Schreier generator of the first step
    obtain ⟨θ', hθ'top, hθ'AS⟩ :=
      exists_artinSchreier_generator p (F := N) (E := M') hM'rank
    set θ : E := M'.val θ' with hθ
    have hadj : IntermediateField.adjoin N {θ} = M' := by
      have h1 := IntermediateField.adjoin_map N {θ'} M'.val
      rw [hθ'top, Set.image_singleton] at h1
      rw [hθ, ← h1, ← AlgHom.fieldRange_eq_map, IntermediateField.fieldRange_val]
    have hsup : N ⊔ IntermediateField.adjoin F {θ} = N' := by
      rw [hN', ← hadj, IntermediateField.restrictScalars_adjoin_eq_sup]
    have hASθ : θ ^ p - θ ∈ N := by
      obtain ⟨c, hc⟩ := hθ'AS
      have hval : θ ^ p - θ = M'.val (θ' ^ p - θ') := by rw [map_sub, map_pow, hθ]
      rw [hval, ← hc, AlgHom.commutes]
      exact c.2
    -- assemble: prepend `N` to the chain
    refine ⟨r + 1, Fin.cons N M, Fin.cons_zero _ _, ?_, ?_⟩
    · rw [← Fin.succ_last, Fin.cons_succ]
      exact hMlast
    · intro i
      induction i using Fin.cases with
      | zero =>
        refine ⟨θ, ?_, ?_⟩
        · rw [Fin.castSucc_zero, Fin.cons_zero]
          exact hASθ
        · rw [Fin.castSucc_zero, Fin.cons_zero, Fin.cons_succ, hM0]
          exact hsup.symm
      | succ j =>
        obtain ⟨θj, hθj1, hθj2⟩ := hMstep j
        refine ⟨θj, ?_, ?_⟩
        · rw [← Fin.succ_castSucc, Fin.cons_succ]
          exact hθj1
        · rw [← Fin.succ_castSucc, Fin.cons_succ, Fin.cons_succ]
          exact hθj2

namespace Ext

open LaurentSeries
open scoped Valued

variable {K : Type*} [Field K] [IsAlgClosed K]
variable {L : Type*} [Field L] [Algebra K⸨X⸩ L] [Module.Finite K⸨X⸩ L]

/-- **The Artin–Schreier tower over `K⸨X⸩`** (Kedlaya 2001a, Lemma 3, Galois case): a
finite Galois extension `L` of `B = K⸨X⸩` (`K` algebraically closed of characteristic
`p`) admits a chain `B(u) = M₀ ≤ M₁ ≤ ⋯ ≤ M_r = ⊤` of intermediate fields in which
`u ^ n = X` for some `n` prime to `p` and each step is generated by an Artin–Schreier
element: `M_{i+1} = M_i(θ_i)` with `θ_i^p - θ_i ∈ M_i`. -/
theorem exists_artinSchreier_tower (p : ℕ) [Fact p.Prime] [CharP K p] [IsGalois K⸨X⸩ L] :
    ∃ (n : ℕ) (u : L) (r : ℕ) (M : Fin (r + 1) → IntermediateField K⸨X⸩ L),
      (n : K) ≠ 0 ∧
      u ^ n = algebraMap K⸨X⸩ L (HahnSeries.single 1 1) ∧
      M 0 = IntermediateField.adjoin K⸨X⸩ {u} ∧
      M (Fin.last r) = ⊤ ∧
      ∀ i : Fin r, ∃ θ : L, θ ^ p - θ ∈ M i.castSucc ∧
        M i.succ = M i.castSucc ⊔ IntermediateField.adjoin K⸨X⸩ {θ} := by
  have hCharB : CharP K⸨X⸩ p := charP_of_injective_algebraMap (algebraMap K K⸨X⸩).injective p
  -- a uniformizer of `L`
  obtain ⟨π, hπ, hall⟩ := exists_spectralNorm_uniformizer_pow_finrank (K := K) (L := L)
  have hq0 : (0 : ℝ) < ‖(HahnSeries.single 1 1 : K⸨X⸩)‖ := norm_X_pos
  have hπ0 : π ≠ 0 := by
    rintro rfl
    rw [spectralNorm_zero, zero_pow Module.finrank_pos.ne'] at hπ
    exact hq0.ne' hπ.symm
  set uu : Lˣ := Units.mk0 π hπ0 with huu
  -- the wild inertia subgroup: a normal `p`-Sylow with cyclic prime-to-`p` quotient
  set P : Subgroup (L ≃ₐ[K⸨X⸩] L) := (tameCharacter K uu).ker with hPdef
  have hPp : IsPGroup p P := isPGroup_ker_tameCharacter (u := uu) p hπ
  set N₀ : IntermediateField K⸨X⸩ L := IntermediateField.fixedField P with hN₀
  have hN₀gal : IsGalois K⸨X⸩ N₀ := IsGalois.of_fixedField_normal_subgroup P
  -- `Gal(N₀/B) ≅ G/P` is cyclic of order `n` prime to `p`
  let e := IsGalois.normalAutEquivQuotient P
  have hcyc : IsCyclic (N₀ ≃ₐ[K⸨X⸩] N₀) := by
    rw [← e.isCyclic]
    exact isCyclic_quotient_ker_tameCharacter uu
  have hnp : ¬ p ∣ Module.finrank K⸨X⸩ N₀ := by
    have hcard : Nat.card (N₀ ≃ₐ[K⸨X⸩] N₀) = Module.finrank K⸨X⸩ N₀ :=
      IsGalois.card_aut_eq_finrank _ _
    have hcong : Nat.card ((L ≃ₐ[K⸨X⸩] L) ⧸ P) = Nat.card (N₀ ≃ₐ[K⸨X⸩] N₀) :=
      Nat.card_congr e.toEquiv
    rw [← hcard, ← hcong]
    exact not_dvd_natCard_quotient_ker_tameCharacter p uu
  have hnK : ((Module.finrank K⸨X⸩ N₀ : K)) ≠ 0 := by
    rw [Ne, CharP.cast_eq_zero_iff K p]
    exact hnp
  -- tame-kummer: the fixed field is `B(u)` with `u ^ n = X`
  obtain ⟨u', hu'pow, hu'adj⟩ :=
    exists_pow_finrank_eq_X_adjoin_eq_top_of_isCyclic (K := K) (L := N₀) hnK
  set u : L := N₀.val u' with hu
  have hupow : u ^ Module.finrank K⸨X⸩ N₀ = algebraMap K⸨X⸩ L (HahnSeries.single 1 1) := by
    have hval := congrArg N₀.val hu'pow
    rw [map_pow, AlgHom.commutes] at hval
    exact hval
  have huadj : IntermediateField.adjoin K⸨X⸩ {u} = N₀ := by
    have h1 := IntermediateField.adjoin_map K⸨X⸩ {u'} N₀.val
    rw [hu'adj, Set.image_singleton] at h1
    rw [hu, ← h1, ← AlgHom.fieldRange_eq_map, IntermediateField.fieldRange_val]
  -- `Gal(L/N₀)` is the `p`-group `P`; chain it with Artin–Schreier steps
  have hgalN₀ : IsGalois N₀ L := inferInstance
  have hPgrp : IsPGroup p (L ≃ₐ[N₀] L) :=
    hPp.of_equiv (IntermediateField.subgroupEquivAlgEquiv P)
  obtain ⟨r, M, hM0, hMlast, hMstep⟩ := exists_artinSchreier_chain p N₀ hgalN₀ hPgrp
  exact ⟨Module.finrank K⸨X⸩ N₀, u, r, M, hnK, hupow, by rw [hM0, huadj], hMlast, hMstep⟩

end Ext

end TrustworthyKedlaya
