/-
Copyright (c) 2026 Yijun Yuan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yijun Yuan
-/
module

public import Mathlib.FieldTheory.IsAlgClosed.Basic
public import Mathlib.RingTheory.AdicCompletion.Completeness
public import Mathlib.RingTheory.Henselian
public import Mathlib.RingTheory.LaurentSeries

/-!
# `m`-th roots in `K⟦X⟧` and the `m`-th power decomposition of `K⸨X⸩`

For `m` invertible in the field `K`:

* `TrustworthyKedlaya.exists_pow_eq_of_constantCoeff_one` : every power series with
  constant coefficient `1` is an `m`-th power in `K⟦X⟧`.  This is Hensel's lemma for
  the `X`-adically complete ring `K⟦X⟧` applied to `Y^m - w` at the approximate
  root `1` (the derivative `m` is a unit).
* `TrustworthyKedlaya.exists_single_order_mul_pow` : if moreover `K` is algebraically
  closed, every nonzero Laurent series `f ∈ K⸨X⸩` factors as `f = X^(order f) * y^m`.
  Equivalently, `K⸨X⸩ˣ` modulo `m`-th powers is generated by the class of `X`.

This is Lemma `lem:laurent-mth-power` of the blueprint, the unit analysis inside the
proof of Kedlaya 2001a, Lemma 3.
-/

@[expose] public section

namespace TrustworthyKedlaya

open PowerSeries

/-- **Hensel's lemma for `m`-th roots in `K⟦X⟧`**: if `m` is invertible in `K`, every
power series with constant coefficient `1` is the `m`-th power of a power series with
constant coefficient `1`. -/
theorem exists_pow_eq_of_constantCoeff_one {K : Type*} [Field K] (m : ℕ) (hm : (m : K) ≠ 0)
    {w : K⟦X⟧} (hw : constantCoeff w = 1) :
    ∃ y : K⟦X⟧, constantCoeff y = 1 ∧ y ^ m = w := by
  have hm0 : m ≠ 0 := fun h => hm (by rw [h, Nat.cast_zero])
  -- Hensel's lemma in the `X`-adically complete ring `K⟦X⟧`, for `Y^m - w` at `1`.
  obtain ⟨y, hroot, hy⟩ := HenselianRing.is_henselian (R := K⟦X⟧)
    (I := Ideal.span {(X : K⟦X⟧)})
    (Polynomial.X ^ m - Polynomial.C w) (Polynomial.monic_X_pow_sub_C w hm0) 1
    (by
      rw [Polynomial.eval_sub, Polynomial.eval_pow, Polynomial.eval_X, Polynomial.eval_C,
        one_pow, Ideal.mem_span_singleton, PowerSeries.X_dvd_iff, map_sub, map_one, hw,
        sub_self])
    (by
      have heval : (Polynomial.X ^ m - Polynomial.C w : Polynomial K⟦X⟧).derivative.eval 1
          = (m : K⟦X⟧) := by
        rw [Polynomial.derivative_sub, Polynomial.derivative_C, sub_zero,
          Polynomial.derivative_X_pow, Polynomial.eval_mul, Polynomial.eval_C,
          Polynomial.eval_pow, Polynomial.eval_X, one_pow, mul_one]
      rw [heval]
      refine IsUnit.map _ (isUnit_iff_constantCoeff.mpr ?_)
      rw [map_natCast]
      exact (isUnit_iff_ne_zero).mpr hm)
  refine ⟨y, ?_, ?_⟩
  · -- `y ≡ 1 mod (X)` gives constant coefficient `1`.
    rw [Ideal.mem_span_singleton, PowerSeries.X_dvd_iff, map_sub, map_one,
      sub_eq_zero] at hy
    exact hy
  · have := hroot
    rw [Polynomial.IsRoot, Polynomial.eval_sub, Polynomial.eval_pow, Polynomial.eval_X,
      Polynomial.eval_C, sub_eq_zero] at this
    exact this

open LaurentSeries in
/-- **The `m`-th power decomposition of `K⸨X⸩`**: over an algebraically closed field in
which `m` is invertible, every nonzero Laurent series `f` factors as
`f = X^(order f) * y^m`.  Equivalently, modulo `m`-th powers every nonzero Laurent
series is a power of `X`. -/
theorem exists_single_order_mul_pow {K : Type*} [Field K] [IsAlgClosed K] (m : ℕ)
    (hm : (m : K) ≠ 0) {f : K⸨X⸩} (hf : f ≠ 0) :
    ∃ y : K⸨X⸩, y ≠ 0 ∧ f = HahnSeries.single f.order 1 * y ^ m := by
  have hm0 : 0 < m := Nat.pos_of_ne_zero fun h => hm (by rw [h, Nat.cast_zero])
  -- The power series part has nonzero constant coefficient `c`.
  set g := f.powerSeriesPart with hg
  have hc0 : constantCoeff g ≠ 0 := by
    rw [hg, ← PowerSeries.coeff_zero_eq_constantCoeff_apply, powerSeriesPart_coeff,
      Nat.cast_zero, add_zero]
    exact fun h => hf (HahnSeries.coeff_order_eq_zero.mp h)
  set c := constantCoeff g with hc
  -- Normalize to a one-unit and extract its `m`-th root by Hensel's lemma,
  -- and an `m`-th root of `c` from algebraic closedness.
  have hw : constantCoeff (PowerSeries.C c⁻¹ * g) = 1 := by
    rw [map_mul, PowerSeries.constantCoeff_C, ← hc, inv_mul_cancel₀ hc0]
  obtain ⟨y₁, hy₁, hy₁m⟩ := exists_pow_eq_of_constantCoeff_one m hm hw
  obtain ⟨b, hb⟩ := IsAlgClosed.exists_pow_nat_eq c hm0
  -- The `m`-th root of the power series part.
  have hbne : b ≠ 0 := by
    rintro rfl
    exact hc0 (by rw [← hb, zero_pow hm0.ne'])
  have hgpow : (PowerSeries.C b * y₁) ^ m = g := by
    rw [mul_pow, ← map_pow, hb, hy₁m, ← mul_assoc, ← map_mul, mul_inv_cancel₀ hc0, map_one,
      one_mul]
  refine ⟨HahnSeries.ofPowerSeries ℤ K (PowerSeries.C b * y₁), ?_, ?_⟩
  · -- Nonvanishing: the constant coefficient of `C b * y₁` is `b ≠ 0`.
    intro h
    rw [map_eq_zero_iff _ HahnSeries.ofPowerSeries_injective] at h
    apply hbne
    have := congrArg constantCoeff h
    rwa [map_mul, PowerSeries.constantCoeff_C, hy₁, mul_one, map_zero] at this
  · rw [← map_pow, hgpow]
    exact f.single_order_mul_powerSeriesPart.symm

end TrustworthyKedlaya
