/-
Copyright (c) 2026 Yijun Yuan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yijun Yuan
-/
module

public import TrustworthyKedlaya.Lp.QpCUn
public import Mathlib.FieldTheory.Extension
public import Mathlib.FieldTheory.Finite.GaloisField
public import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
public import Mathlib.NumberTheory.Padics.ProperSpace
public import Mathlib.NumberTheory.Padics.RingHoms
public import Mathlib.RingTheory.AdicCompletion.Noetherian
public import Mathlib.RingTheory.DedekindDomain.IntegralClosure
public import Mathlib.RingTheory.Henselian
public import Mathlib.RingTheory.Nakayama
public import Mathlib.RingTheory.Unramified.Field
public import Mathlib.RingTheory.Unramified.Finite

/-!
# The maximal unramified extension `ℚᵘⁿ_[p]` of `ℚ_[p]`

`TrustworthyKedlaya.Lp.QpCUn` realizes the *completed* maximal unramified extension
`ℚᶜᵘⁿ_[p]` of `ℚ_[p]` as the fraction field of `ℤᶜᵘⁿ_[p] = W(𝔽ᵃ_[p])`. This file carves out
the (uncompleted) maximal unramified extension `ℚᵘⁿ_[p]` inside it and proves that it deserves
its name:

- `ℤᵘⁿ_[p]` is the subring of `W(𝔽ᵃ_[p])` consisting of the Witt vectors all of whose
  coefficients lie in a common finite subfield `𝔽_{p^r} ⊆ 𝔽ᵃ_[p]`; equivalently, it is the
  union of the images of the Witt vector rings `W(𝔽_{p^r})`, `r ≥ 1` (`W(𝔽_{p^r})` is the ring
  of integers of the unramified extension of degree `r`);
- `ℚᵘⁿ_[p]` is the fraction field of `ℤᵘⁿ_[p]`, realized as the subfield of `ℚᶜᵘⁿ_[p]`
  generated by `ℤᵘⁿ_[p]`.

`ℚ_[p]` embeds into `ℚᵘⁿ_[p]` (through `TrustworthyKedlaya.QpCUn.Qp_embd`), and `ℚᵘⁿ_[p]` is
dense in `ℚᶜᵘⁿ_[p]`: truncating the Witt vector expansion of an element of `ℤᶜᵘⁿ_[p]` after `N`
coefficients produces an element of `ℤᵘⁿ_[p]` congruent to it modulo `p ^ N`.

**Maximality.** Two statements make `ℚᵘⁿ_[p]` *the maximal unramified extension* of `ℚ_[p]`:

1. *`ℚᵘⁿ_[p]` is unramified*: its ring of integers is formally unramified over `ℤ_[p]`,
   `Algebra.FormallyUnramified ℤ_[p] ℤᵘⁿ_[p]` (i.e. `Ω[ℤᵘⁿ_[p]⁄ℤ_[p]] = 0`), and each finite
   layer `W(𝔽_{p^r})` is an unramified `ℤ_[p]`-algebra in the sense of `Algebra.Unramified`.
   The proof shows that `W(𝔽_{p^r})` is `ℤ_[p]`-spanned by the Teichmüller lifts `[α]`,
   `α ∈ 𝔽_{p^r}` (a compactness argument in `ℚᶜᵘⁿ_[p]`), and that every `ℤ_[p]`-derivation kills
   `[α]` because `[α] ^ (p ^ r) = [α]` and `1 - p ^ r [α] ^ (p ^ r - 1)` is a unit.
2. *`ℚᵘⁿ_[p]` contains every unramified extension*: a finite extension `L/ℚ_[p]` whose ring of
   integers `integralClosure ℤ_[p] L` is (formally) unramified over `ℤ_[p]` admits a
   `ℚ_[p]`-embedding `L →ₐ[ℚ_[p]] ℚᵘⁿ_[p]`. The proof uses that `𝒪_L` is finite free over
   `ℤ_[p]`, hence `p`-adically complete and Henselian; unramifiedness makes `𝒪_L / p 𝒪_L` a
   finite reduced `𝔽_p`-algebra, on which some Frobenius power `x ↦ x ^ (p ^ N)` is the
   identity; Hensel's lemma lifts every residue class to a root of `X ^ (p ^ N) - X` (a
   Teichmüller representative); by Nakayama these roots span `𝒪_L`, hence generate `L`, and
   `X ^ (p ^ N) - X` splits over `ℚᵘⁿ_[p]` (its roots there are the Teichmüller lifts of
   `𝔽_{p^N}`), so `L` embeds into `ℚᵘⁿ_[p]`.

We also show that `ℚᵘⁿ_[p]` is exactly the set of Frobenius-periodic elements of `ℚᶜᵘⁿ_[p]`,
and that every element of `ℚᶜᵘⁿ_[p]` algebraic over `ℚ_[p]` lies in `ℚᵘⁿ_[p]`.

## Main definitions

- `TrustworthyKedlaya.OQpUn` (`ℤᵘⁿ_[p]`): the subring `⋃ᵣ W(𝔽_{p^r})` of `ℤᶜᵘⁿ_[p]`.
- `TrustworthyKedlaya.QpUn` (`ℚᵘⁿ_[p]`): the subfield `Frac(ℤᵘⁿ_[p])` of `ℚᶜᵘⁿ_[p]`.
- `TrustworthyKedlaya.QpUn.Qp_embd`: the embedding `ℚ_[p] →+* ℚᵘⁿ_[p]`.
- `TrustworthyKedlaya.wittSubring`: the layer `W(K) ⊆ ℤᶜᵘⁿ_[p]` for a subfield `K ⊆ 𝔽ᵃ_[p]`.
- `TrustworthyKedlaya.QpCUn.frobenius`: the Frobenius of `ℚᶜᵘⁿ_[p]`, extending the Witt vector
  Frobenius of `ℤᶜᵘⁿ_[p]`.

## Main statements

- `TrustworthyKedlaya.mem_OQpUn_iff_exists_pow_eq`: `x ∈ ℤᵘⁿ_[p]` iff some power of Frobenius
  fixes every coefficient of `x`, i.e. `x.coeff n ^ p ^ r = x.coeff n` for all `n` and a single
  `r ≥ 1`.
- `TrustworthyKedlaya.range_map_le_OQpUn`, `TrustworthyKedlaya.exists_galoisField_of_mem_OQpUn`:
  `ℤᵘⁿ_[p]` is exactly the union of the images of `W(GaloisField p r) → W(𝔽ᵃ_[p])`.
- `TrustworthyKedlaya.QpUn.instIsFractionRing`: `ℚᵘⁿ_[p]` is the fraction field of `ℤᵘⁿ_[p]`.
- `TrustworthyKedlaya.QpUn.dense`: `ℚᵘⁿ_[p]` is dense in `ℚᶜᵘⁿ_[p]`.
- `TrustworthyKedlaya.mem_QpUn_iff_exists_iterate_frobenius_eq`: `ℚᵘⁿ_[p]` is the set of elements
  of `ℚᶜᵘⁿ_[p]` fixed by a positive power of Frobenius.
- `TrustworthyKedlaya.mem_QpUn_of_isAlgebraic`: elements of `ℚᶜᵘⁿ_[p]` algebraic over `ℚ_[p]` lie
  in `ℚᵘⁿ_[p]`.
- `TrustworthyKedlaya.exists_eq_sum_smul_teichmuller_of_mem_wittSubring`,
  `TrustworthyKedlaya.wittSubring.instModuleFinite`: `W(𝔽_{p^r})` is `ℤ_[p]`-spanned by Teichmüller
  lifts, hence a finite `ℤ_[p]`-module.
- `TrustworthyKedlaya.OQpUn.instFormallyUnramified`: `Algebra.FormallyUnramified ℤ_[p] ℤᵘⁿ_[p]`.
- `TrustworthyKedlaya.wittSubring.instUnramified`: `Algebra.Unramified ℤ_[p] (W(𝔽_{p^r}))`.
- `TrustworthyKedlaya.QpUn.nonempty_algHom_of_formallyUnramified`,
  `TrustworthyKedlaya.QpUn.nonempty_algHom_of_unramified`: every finite extension of `ℚ_[p]` with
  unramified ring of integers embeds into `ℚᵘⁿ_[p]` over `ℚ_[p]`.

## Implementation notes

`ℚᶜᵘⁿ_[p]` is a `WithVal` type, which carries both `WithVal.instDivisionRing` and
`WithVal.instField`. These are not reducibly defeq, and with both present `Field ↥S` cannot be
synthesized for a subfield `S` of `ℚᶜᵘⁿ_[p]`. We therefore disable `WithVal.instDivisionRing` in
this file (`attribute [-instance]`), so that `ℚᵘⁿ_[p] : Subfield ℚᶜᵘⁿ_[p]` is built on
`Field.toDivisionRing`. Downstream files working with subfields of `ℚᶜᵘⁿ_[p]` may need the same
attribute erasure.

## Notation

- `ℤᵘⁿ_[p]`, `ℚᵘⁿ_[p]` for the two objects above.

## Tags

p-adic, Witt vector, unramified extension, maximal unramified extension
-/

@[expose] public section

/- `WithVal.instDivisionRing` is not reducibly defeq to `Field.toDivisionRing` of
`WithVal.instField`; with both present, `Subfield ℚᶜᵘⁿ_[p]` is elaborated against the former and
`Field ↥S` cannot be synthesized for `S : Subfield ℚᶜᵘⁿ_[p]`. We disable the redundant instance in
this file, so that `ℚᵘⁿ_[p]` is a `Subfield` of `ℚᶜᵘⁿ_[p]` viewed as a field. -/
attribute [-instance] WithVal.instDivisionRing

namespace TrustworthyKedlaya

open TrustworthyKedlaya WittVector

variable (p : ℕ) [Fact (Nat.Prime p)]

/-! ### Witt vectors with coefficients in a subfield -/

/-- The Witt vectors over `𝔽ᵃ_[p]` all of whose coefficients lie in the intermediate field `K`,
i.e. the image of `W(K) → W(𝔽ᵃ_[p])`. -/
noncomputable def wittSubring (K : IntermediateField (ZMod p) 𝔽ᵃ_[p]) : Subring ℤᶜᵘⁿ_[p] :=
  (WittVector.map (K.val : K →+* 𝔽ᵃ_[p])).range

theorem mem_wittSubring_iff {K : IntermediateField (ZMod p) 𝔽ᵃ_[p]} {x : ℤᶜᵘⁿ_[p]} :
    x ∈ wittSubring p K ↔ ∀ n, x.coeff n ∈ K := by
  constructor
  · rintro ⟨y, rfl⟩ n
    rw [map_coeff]
    exact (y.coeff n).2
  · intro h
    exact ⟨WittVector.mk p fun n => ⟨x.coeff n, h n⟩, WittVector.ext fun n => by simp [map_coeff]⟩

theorem wittSubring_mono {K L : IntermediateField (ZMod p) 𝔽ᵃ_[p]} (h : K ≤ L) :
    wittSubring p K ≤ wittSubring p L := fun _ hx =>
  (mem_wittSubring_iff p).2 fun n => h ((mem_wittSubring_iff p).1 hx n)

/-! ### The ring of integers `ℤᵘⁿ_[p]` -/

/-- The ring of integers `ℤᵘⁿ_[p]` of the maximal unramified extension of `ℚ_[p]`: the subring of
`ℤᶜᵘⁿ_[p] = W(𝔽ᵃ_[p])` of Witt vectors whose coefficients all lie in a common finite subfield of
`𝔽ᵃ_[p]`. It is the union of the images of the `W(𝔽_{p^r})`, `r ≥ 1`. -/
def OQpUn : Subring ℤᶜᵘⁿ_[p] where
  carrier := {x | ∃ K : IntermediateField (ZMod p) 𝔽ᵃ_[p],
    FiniteDimensional (ZMod p) K ∧ ∀ n, x.coeff n ∈ K}
  zero_mem' := ⟨⊥, inferInstance, fun n => by simp⟩
  one_mem' := ⟨⊥, inferInstance, fun n => by
    rcases n with _ | n
    · simp
    · simp⟩
  add_mem' := by
    rintro x y ⟨K, hK, hx⟩ ⟨L, hL, hy⟩
    refine ⟨K ⊔ L, IntermediateField.finiteDimensional_sup K L, (mem_wittSubring_iff p).1 ?_⟩
    exact add_mem (wittSubring_mono p le_sup_left ((mem_wittSubring_iff p).2 hx))
      (wittSubring_mono p le_sup_right ((mem_wittSubring_iff p).2 hy))
  mul_mem' := by
    rintro x y ⟨K, hK, hx⟩ ⟨L, hL, hy⟩
    refine ⟨K ⊔ L, IntermediateField.finiteDimensional_sup K L, (mem_wittSubring_iff p).1 ?_⟩
    exact mul_mem (wittSubring_mono p le_sup_left ((mem_wittSubring_iff p).2 hx))
      (wittSubring_mono p le_sup_right ((mem_wittSubring_iff p).2 hy))
  neg_mem' := by
    rintro x ⟨K, hK, hx⟩
    exact ⟨K, hK, (mem_wittSubring_iff p).1 (neg_mem ((mem_wittSubring_iff p).2 hx))⟩

@[inherit_doc] notation "ℤᵘⁿ_[" p "]" => OQpUn p

theorem mem_OQpUn_iff {x : ℤᶜᵘⁿ_[p]} :
    x ∈ ℤᵘⁿ_[p] ↔ ∃ K : IntermediateField (ZMod p) 𝔽ᵃ_[p],
      FiniteDimensional (ZMod p) K ∧ ∀ n, x.coeff n ∈ K :=
  Iff.rfl

theorem wittSubring_le_OQpUn (K : IntermediateField (ZMod p) 𝔽ᵃ_[p])
    [FiniteDimensional (ZMod p) K] : wittSubring p K ≤ ℤᵘⁿ_[p] := fun x hx =>
  ⟨K, ‹_›, (mem_wittSubring_iff p).1 hx⟩

/-- A Witt vector with only finitely many distinct coefficients lies in `ℤᵘⁿ_[p]`. -/
theorem mem_OQpUn_of_finite_range {x : ℤᶜᵘⁿ_[p]} (hx : (Set.range x.coeff).Finite) :
    x ∈ ℤᵘⁿ_[p] := by
  have := hx.to_subtype
  refine ⟨IntermediateField.adjoin (ZMod p) (Set.range x.coeff), ?_, fun n => ?_⟩
  · exact IntermediateField.finiteDimensional_adjoin fun a _ => Algebra.IsIntegral.isIntegral a
  · exact IntermediateField.subset_adjoin _ _ ⟨n, rfl⟩

/-- Teichmüller lifts lie in `ℤᵘⁿ_[p]`. -/
theorem teichmuller_mem_OQpUn (a : 𝔽ᵃ_[p]) : teichmuller p a ∈ ℤᵘⁿ_[p] := by
  refine ⟨IntermediateField.adjoin (ZMod p) {a},
    IntermediateField.adjoin.finiteDimensional (Algebra.IsIntegral.isIntegral a), fun n => ?_⟩
  rcases n with _ | n
  · rw [teichmuller_coeff_zero]
    exact IntermediateField.mem_adjoin_simple_self _ _
  · rw [teichmuller_coeff_pos p a _ n.succ_pos]
    exact zero_mem _

/-! ### `ℤᵘⁿ_[p]` as the union of the `W(𝔽_{p^r})` -/

/-- The image of `W(𝔽_{p^r})` under any embedding `𝔽_{p^r} → 𝔽ᵃ_[p]` lies in `ℤᵘⁿ_[p]`. -/
theorem range_map_le_OQpUn (r : ℕ) (f : GaloisField p r →ₐ[ZMod p] 𝔽ᵃ_[p]) :
    (WittVector.map (f : GaloisField p r →+* 𝔽ᵃ_[p])).range ≤ ℤᵘⁿ_[p] := by
  rintro x ⟨y, rfl⟩
  have : FiniteDimensional (ZMod p) f.fieldRange :=
    LinearEquiv.finiteDimensional (AlgEquiv.ofInjectiveField f).toLinearEquiv
  refine ⟨f.fieldRange, inferInstance, fun n => ?_⟩
  rw [map_coeff]
  exact ⟨y.coeff n, rfl⟩

/-- Every element of `ℤᵘⁿ_[p]` lies in the image of `W(𝔽_{p^r})` for some `r ≥ 1` and some
embedding `𝔽_{p^r} → 𝔽ᵃ_[p]`. -/
theorem exists_galoisField_of_mem_OQpUn {x : ℤᶜᵘⁿ_[p]} (hx : x ∈ ℤᵘⁿ_[p]) :
    ∃ (r : ℕ) (f : GaloisField p r →ₐ[ZMod p] 𝔽ᵃ_[p]), 0 < r ∧
      x ∈ (WittVector.map (f : GaloisField p r →+* 𝔽ᵃ_[p])).range := by
  obtain ⟨K, hK, hx⟩ := hx
  have : Finite K := Module.finite_of_finite (ZMod p)
  have hcard : Nat.card K = p ^ Module.finrank (ZMod p) K := by
    rw [Module.natCard_eq_pow_finrank (K := ZMod p), Nat.card_zmod]
  let e : K ≃ₐ[ZMod p] GaloisField p (Module.finrank (ZMod p) K) :=
    GaloisField.algEquivGaloisField p _ hcard
  refine ⟨Module.finrank (ZMod p) K, K.val.comp e.symm.toAlgHom, Module.finrank_pos, ?_⟩
  refine ⟨WittVector.mk p fun n => e ⟨x.coeff n, hx n⟩, WittVector.ext fun n => ?_⟩
  simp [map_coeff]

/-! ### Frobenius characterization -/

/-- The finite subfield `𝔽_{p^r} ⊆ 𝔽ᵃ_[p]`: the fixed field of the `r`-th iterate of Frobenius,
i.e. the roots of `X ^ p ^ r - X`. -/
noncomputable def frobeniusFixed (r : ℕ) : IntermediateField (ZMod p) 𝔽ᵃ_[p] :=
  (RingHom.eqLocusField (iterateFrobenius 𝔽ᵃ_[p] p r) (RingHom.id _)).toIntermediateField
    fun a => by
      rw [RingHom.mem_eqLocusField, iterateFrobenius_def, RingHom.id_apply, ← map_pow,
        ZMod.pow_card_pow]

theorem mem_frobeniusFixed_iff {r : ℕ} {a : 𝔽ᵃ_[p]} :
    a ∈ frobeniusFixed p r ↔ a ^ p ^ r = a :=
  RingHom.mem_eqLocusField.trans (by rw [iterateFrobenius_def, RingHom.id_apply])

/-- For `r ≥ 1`, the fixed field of `Frob ^ r` is finite. -/
theorem finite_frobeniusFixed {r : ℕ} (hr : 0 < r) : Finite (frobeniusFixed p r) := by
  have hp1 : 1 < p ^ r := Nat.one_lt_pow hr.ne' (Fact.out : Nat.Prime p).one_lt
  have hne : (Polynomial.X ^ p ^ r - Polynomial.X : Polynomial 𝔽ᵃ_[p]) ≠ 0 := by
    intro h0
    have h1 := congrArg (fun P : Polynomial 𝔽ᵃ_[p] => P.coeff 1) h0
    simp [Polynomial.coeff_X_pow, hp1.ne] at h1
  have hfin : {a : 𝔽ᵃ_[p] | a ^ p ^ r = a}.Finite := by
    refine (Polynomial.finite_setOfPred_isRoot hne).subset fun a ha => ?_
    simp only [Set.mem_ofPred_eq, Polynomial.IsRoot.def, Polynomial.eval_sub, Polynomial.eval_pow,
      Polynomial.eval_X, sub_eq_zero]
    exact ha
  have hset : (frobeniusFixed p r : Set 𝔽ᵃ_[p]) = {a : 𝔽ᵃ_[p] | a ^ p ^ r = a} := by
    ext a
    exact mem_frobeniusFixed_iff p
  have hfin' : (frobeniusFixed p r : Set 𝔽ᵃ_[p]).Finite := by
    rw [hset]
    exact hfin
  exact hfin'.to_subtype

instance (r : ℕ) [NeZero r] : FiniteDimensional (ZMod p) (frobeniusFixed p r) :=
  haveI := finite_frobeniusFixed p (NeZero.pos r)
  Module.Finite.of_finite

/-- `x ∈ ℤᵘⁿ_[p]` if and only if a single power `Frob ^ r`, `r ≥ 1`, of Frobenius fixes every
coefficient of `x`; i.e. all coefficients of `x` lie in one finite subfield `𝔽_{p^r}`. -/
theorem mem_OQpUn_iff_exists_pow_eq {x : ℤᶜᵘⁿ_[p]} :
    x ∈ ℤᵘⁿ_[p] ↔ ∃ r : ℕ, 0 < r ∧ ∀ n, x.coeff n ^ p ^ r = x.coeff n := by
  constructor
  · rintro ⟨K, hK, hx⟩
    have : Finite K := Module.finite_of_finite (ZMod p)
    have : Fintype K := Fintype.ofFinite K
    refine ⟨Module.finrank (ZMod p) K, Module.finrank_pos, fun n => ?_⟩
    have hcard : Fintype.card K = p ^ Module.finrank (ZMod p) K := by
      rw [← Nat.card_eq_fintype_card, Module.natCard_eq_pow_finrank (K := ZMod p), Nat.card_zmod]
    have := FiniteField.pow_card (⟨x.coeff n, hx n⟩ : K)
    rw [hcard] at this
    exact congrArg Subtype.val this
  · rintro ⟨r, hr, hx⟩
    have : NeZero r := ⟨hr.ne'⟩
    exact ⟨frobeniusFixed p r, inferInstance, fun n => (mem_frobeniusFixed_iff p).2 (hx n)⟩

/-! ### The maximal unramified extension `ℚᵘⁿ_[p]` -/

/-- The maximal unramified extension `ℚᵘⁿ_[p]` of `ℚ_[p]`: the fraction field of `ℤᵘⁿ_[p]`,
realized as the subfield of `ℚᶜᵘⁿ_[p]` generated by (the image of) `ℤᵘⁿ_[p]`. -/
noncomputable def QpUn : Subfield ℚᶜᵘⁿ_[p] :=
  Subfield.closure ((ℤᵘⁿ_[p]).map (algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p]))

@[inherit_doc] notation "ℚᵘⁿ_[" p "]" => QpUn p

namespace QpUn

theorem algebraMap_mem {a : ℤᶜᵘⁿ_[p]} (ha : a ∈ ℤᵘⁿ_[p]) :
    algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] a ∈ ℚᵘⁿ_[p] :=
  Subfield.subset_closure ⟨a, ha, rfl⟩

/-- `x ∈ ℚᵘⁿ_[p]` if and only if `x = a / b` with `a, b ∈ ℤᵘⁿ_[p]`. -/
theorem mem_iff {x : ℚᶜᵘⁿ_[p]} :
    x ∈ ℚᵘⁿ_[p] ↔ ∃ a ∈ ℤᵘⁿ_[p], ∃ b ∈ ℤᵘⁿ_[p],
      algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] a / algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] b = x := by
  rw [QpUn]
  refine Subfield.mem_closure_iff.trans ?_
  rw [Subring.closure_eq]
  constructor
  · rintro ⟨_, ⟨a, ha, rfl⟩, _, ⟨b, hb, rfl⟩, h⟩
    exact ⟨a, ha, b, hb, h⟩
  · rintro ⟨a, ha, b, hb, h⟩
    exact ⟨_, ⟨a, ha, rfl⟩, _, ⟨b, hb, rfl⟩, h⟩

/-- The structure map `ℤᵘⁿ_[p] → ℚᵘⁿ_[p]`, restricted from `ℤᶜᵘⁿ_[p] → ℚᶜᵘⁿ_[p]`. -/
noncomputable instance : Algebra ℤᵘⁿ_[p] ℚᵘⁿ_[p] :=
  (((algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p]).comp (ℤᵘⁿ_[p]).subtype).codRestrict ℚᵘⁿ_[p]
    fun a => algebraMap_mem p a.2).toAlgebra

@[simp]
theorem coe_algebraMap_apply (a : ℤᵘⁿ_[p]) :
    (algebraMap ℤᵘⁿ_[p] ℚᵘⁿ_[p] a : ℚᶜᵘⁿ_[p]) = algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] a :=
  rfl

instance : IsScalarTower ℤᵘⁿ_[p] ℚᵘⁿ_[p] ℚᶜᵘⁿ_[p] :=
  IsScalarTower.of_algebraMap_eq fun _ => rfl

/-- `ℚᵘⁿ_[p]` is the fraction field of `ℤᵘⁿ_[p]`. -/
instance instIsFractionRing : IsFractionRing ℤᵘⁿ_[p] ℚᵘⁿ_[p] where
  map_units y := by
    have hy : (algebraMap ℤᵘⁿ_[p] ℚᵘⁿ_[p] y : ℚᶜᵘⁿ_[p]) ≠ 0 := by
      rw [coe_algebraMap_apply]
      exact (map_ne_zero_iff _ (IsFractionRing.injective ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p])).2
        (Subtype.coe_ne_coe.2 (nonZeroDivisors.ne_zero y.2))
    exact isUnit_iff_ne_zero.2 fun h => hy (by rw [h, Subfield.coe_zero])
  surj z := by
    obtain ⟨a, ha, b, hb, h⟩ := (mem_iff p).1 z.2
    by_cases hb0 : b = 0
    · refine ⟨(0, 1), Subtype.ext ?_⟩
      simp only [OneMemClass.coe_one, map_one, mul_one, ZeroMemClass.coe_zero, map_zero]
      rw [← h, hb0, map_zero, div_zero]
    · refine ⟨(⟨a, ha⟩, ⟨⟨b, hb⟩, mem_nonZeroDivisors_of_ne_zero
        fun h' => hb0 (congrArg Subtype.val h')⟩), Subtype.ext ?_⟩
      simp only [Subfield.coe_mul, coe_algebraMap_apply]
      rw [← h, div_mul_cancel₀]
      exact (map_ne_zero_iff _ (IsFractionRing.injective ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p])).2 hb0
  exists_of_eq {x y} h := by
    refine ⟨1, ?_⟩
    have := congrArg (fun z : ℚᵘⁿ_[p] => (z : ℚᶜᵘⁿ_[p])) h
    simp only [coe_algebraMap_apply] at this
    rw [OneMemClass.coe_one, one_mul, one_mul]
    exact Subtype.ext (IsFractionRing.injective ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] this)

/-! ### `ℚ_[p] ⊆ ℚᵘⁿ_[p]` -/

/-- The image of `ℤ_[p] → ℤᶜᵘⁿ_[p]` (the map underlying `QpCUn.Qp_embd`) lies in `ℤᵘⁿ_[p]`:
its coefficients lie in the prime field. -/
theorem map_fromPadicInt_mem_OQpUn (a : ℤ_[p]) :
    WittVector.map (algebraMap (ZMod p) 𝔽ᵃ_[p]) (WittVector.fromPadicInt p a) ∈ ℤᵘⁿ_[p] :=
  ⟨⊥, inferInstance, fun n => by
    rw [map_coeff, IntermediateField.mem_bot]
    exact ⟨_, rfl⟩⟩

/-- The embedding `ℚ_[p] → ℚᶜᵘⁿ_[p]` lands in `ℚᵘⁿ_[p]`. -/
theorem Qp_embd_mem (x : ℚ_[p]) : QpCUn.Qp_embd x ∈ ℚᵘⁿ_[p] := by
  obtain ⟨a, b, hb, rfl⟩ := IsFractionRing.div_surjective (A := ℤ_[p]) x
  rw [map_div₀]
  refine div_mem ?_ ?_
  · rw [QpCUn.Qp_embd, IsFractionRing.map, IsLocalization.map_eq]
    exact algebraMap_mem p (map_fromPadicInt_mem_OQpUn p a)
  · rw [QpCUn.Qp_embd, IsFractionRing.map, IsLocalization.map_eq]
    exact algebraMap_mem p (map_fromPadicInt_mem_OQpUn p b)

/-- The canonical embedding `ℚ_[p] → ℚᵘⁿ_[p]`, the restriction of `QpCUn.Qp_embd`. -/
noncomputable def Qp_embd : ℚ_[p] →+* ℚᵘⁿ_[p] :=
  (QpCUn.Qp_embd).codRestrict ℚᵘⁿ_[p] (Qp_embd_mem p)

@[simp]
theorem coe_Qp_embd_apply (x : ℚ_[p]) : (Qp_embd p x : ℚᶜᵘⁿ_[p]) = QpCUn.Qp_embd x :=
  rfl

theorem Qp_embd_fieldRange_le : (QpCUn.Qp_embd (p := p)).fieldRange ≤ ℚᵘⁿ_[p] := by
  rintro _ ⟨x, rfl⟩
  exact Qp_embd_mem p x

/-- `ℚᵘⁿ_[p]` as a `ℚ_[p]`-algebra, via `Qp_embd`. -/
noncomputable instance : Algebra ℚ_[p] ℚᵘⁿ_[p] := (Qp_embd p).toAlgebra

instance : IsScalarTower ℚ_[p] ℚᵘⁿ_[p] ℚᶜᵘⁿ_[p] :=
  IsScalarTower.of_algebraMap_eq fun _ => rfl

/-! ### Density of `ℚᵘⁿ_[p]` in `ℚᶜᵘⁿ_[p]` -/

/-- Truncating the Witt vector expansion of `a ∈ ℤᶜᵘⁿ_[p]` after `N` coefficients gives an
element of `ℤᵘⁿ_[p]` congruent to `a` modulo `p ^ N`. -/
theorem exists_mem_OQpUn_sub_mem_span (a : ℤᶜᵘⁿ_[p]) (N : ℕ) :
    ∃ b ∈ ℤᵘⁿ_[p], a - b ∈ Ideal.span {(p : ℤᶜᵘⁿ_[p]) ^ N} := by
  classical
  refine ⟨WittVector.mk p fun n => if n < N then a.coeff n else 0, ?_, ?_⟩
  · refine mem_OQpUn_of_finite_range p ((Set.finite_range fun i : Fin N => a.coeff i).union
      (Set.finite_singleton 0) |>.subset ?_)
    rintro _ ⟨n, rfl⟩
    rw [coeff_mk]
    split_ifs with h
    · exact Or.inl ⟨⟨n, h⟩, rfl⟩
    · exact Or.inr rfl
  · rw [mem_span_p_pow_iff_le_coeff_eq_zero]
    exact le_coeff_eq_iff_le_sub_coeff_eq_zero.1 fun i hi => by simp [coeff_mk, hi]

/-- Elements of `p ^ N ℤᶜᵘⁿ_[p]` have valuation at most `p ^ (-N)` in `ℚᶜᵘⁿ_[p]`. -/
theorem valued_algebraMap_le_of_mem_span {r : ℤᶜᵘⁿ_[p]} {N : ℕ}
    (h : r ∈ Ideal.span {(p : ℤᶜᵘⁿ_[p]) ^ N}) :
    Valued.v (algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] r) ≤ WithZero.exp (-(N : ℤ)) := by
  have hmax : (IsDiscreteValuationRing.maximalIdeal ℤᶜᵘⁿ_[p]).asIdeal =
      Ideal.span {(p : ℤᶜᵘⁿ_[p])} := (WittVector.irreducible p).maximalIdeal_eq
  rw [QpCUn.valued_algebraMap, IsDedekindDomain.HeightOneSpectrum.intValuation_le_pow_iff_mem,
    hmax, Ideal.span_singleton_pow]
  exact h

/-- `Valued.v (p ^ k) = p ^ (-k)` in `ℚᶜᵘⁿ_[p]`. -/
theorem valued_algebraMap_p_pow (k : ℕ) :
    Valued.v (algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] ((p : ℤᶜᵘⁿ_[p]) ^ k)) = WithZero.exp (-(k : ℤ)) := by
  have hmax : (IsDiscreteValuationRing.maximalIdeal ℤᶜᵘⁿ_[p]).asIdeal =
      Ideal.span {(p : ℤᶜᵘⁿ_[p])} := (WittVector.irreducible p).maximalIdeal_eq
  rw [QpCUn.valued_algebraMap, map_pow,
    (IsDiscreteValuationRing.maximalIdeal ℤᶜᵘⁿ_[p]).intValuation_singleton
      (WittVector.p_nonzero p _) hmax, ← WithZero.exp_nsmul]
  congr 1
  simp

/-- Every element of `ℚᶜᵘⁿ_[p]` is approximated to within `p ^ (-N)` by an element of
`ℚᵘⁿ_[p]`. -/
theorem exists_mem_valued_sub_le (x : ℚᶜᵘⁿ_[p]) (N : ℕ) :
    ∃ z ∈ ℚᵘⁿ_[p], Valued.v (x - z) ≤ WithZero.exp (-(N : ℤ)) := by
  obtain ⟨a, b, hb, rfl⟩ := IsFractionRing.div_surjective (A := ℤᶜᵘⁿ_[p]) x
  obtain ⟨k, u, rfl⟩ := IsDiscreteValuationRing.eq_unit_mul_pow_irreducible
    (nonZeroDivisors.ne_zero hb) (WittVector.irreducible p)
  obtain ⟨c, hc, hsub⟩ := exists_mem_OQpUn_sub_mem_span p (a * ↑u⁻¹) (N + k)
  have hinj := IsFractionRing.injective ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p]
  have hpk : algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] ((p : ℤᶜᵘⁿ_[p]) ^ k) ≠ 0 :=
    (map_ne_zero_iff _ hinj).2 (pow_ne_zero _ (WittVector.p_nonzero p _))
  have hu : algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] (u : ℤᶜᵘⁿ_[p]) ≠ 0 :=
    (map_ne_zero_iff _ hinj).2 u.ne_zero
  refine ⟨algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] c / algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] ((p : ℤᶜᵘⁿ_[p]) ^ k),
    div_mem (algebraMap_mem p hc) (algebraMap_mem p (pow_mem (natCast_mem _ p) k)), ?_⟩
  have heq : algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] a /
        algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] (↑u * (p : ℤᶜᵘⁿ_[p]) ^ k) -
      algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] c / algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] ((p : ℤᶜᵘⁿ_[p]) ^ k) =
      algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] (a * ↑u⁻¹ - c) /
        algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] ((p : ℤᶜᵘⁿ_[p]) ^ k) := by
    rw [map_sub, map_mul, map_mul, map_units_inv]
    ring
  rw [heq, map_div₀, valued_algebraMap_p_pow, div_le_iff₀ WithZero.exp_pos, ← WithZero.exp_add]
  refine (valued_algebraMap_le_of_mem_span p hsub).trans ?_
  rw [WithZero.exp_le_exp]
  push_cast
  omega

/-- `ℚᵘⁿ_[p]` is dense in `ℚᶜᵘⁿ_[p]`. -/
theorem dense : Dense (ℚᵘⁿ_[p] : Set ℚᶜᵘⁿ_[p]) := by
  intro x
  rw [mem_closure_iff_nhds]
  intro t ht
  obtain ⟨γ, hγ⟩ := Valued.mem_nhds.1 ht
  set g : WithZero (Multiplicative ℤ) := MonoidWithZeroHom.ValueGroup₀.embedding γ.1 with hg
  have hg0 : g ≠ 0 := MonoidWithZeroHom.ValueGroup₀.embedding_unit_ne_zero γ
  obtain ⟨z, hz, hle⟩ := exists_mem_valued_sub_le p x (1 - g.log).toNat
  refine ⟨z, hγ ?_, hz⟩
  simp only [Set.mem_ofPred_eq]
  rw [Valuation.restrict_lt_iff_lt_embedding, ← hg, Valuation.map_sub_swap]
  refine lt_of_le_of_lt hle ?_
  rw [← WithZero.lt_log_iff_exp_lt hg0]
  by_cases hpos : 1 - g.log ≥ 0
  · rw [Int.toNat_of_nonneg hpos]; omega
  · rw [Int.toNat_of_nonpos (le_of_lt (by omega))]; push_cast; omega

theorem denseRange_subtype : DenseRange (ℚᵘⁿ_[p]).subtype := by
  rw [DenseRange, Subfield.coe_subtype, Subtype.range_coe]
  exact dense p

end QpUn

/-! ### The `ℤ_[p]`-algebra structure on `ℤᶜᵘⁿ_[p]` and `ℚᶜᵘⁿ_[p]` -/

namespace OQpCUn

/-- The canonical embedding `ℤ_[p] = W(𝔽_p) → W(𝔽ᵃ_[p]) = ℤᶜᵘⁿ_[p]`, the map on rings of integers
underlying `TrustworthyKedlaya.QpCUn.Qp_embd`. -/
noncomputable def Zp_embd : ℤ_[p] →+* ℤᶜᵘⁿ_[p] :=
  (WittVector.map (algebraMap (ZMod p) 𝔽ᵃ_[p])).comp (WittVector.fromPadicInt p)

theorem Zp_embd_injective : Function.Injective (Zp_embd p) := by
  simp only [Zp_embd, RingHom.coe_comp]
  refine Function.Injective.comp ?_ ?_
  · exact WittVector.map_injective _ (algebraMap (ZMod p) 𝔽ᵃ_[p]).injective
  · refine Function.injective_iff_hasLeftInverse.mpr ⟨WittVector.toPadicInt p, ?_⟩
    rw [Function.leftInverse_iff_comp]
    ext r
    simpa using toPadicInt_comp_fromPadicInt_ext p r

theorem coeff_Zp_embd (a : ℤ_[p]) (n : ℕ) :
    (Zp_embd p a).coeff n = algebraMap (ZMod p) 𝔽ᵃ_[p] ((WittVector.fromPadicInt p a).coeff n) :=
  map_coeff _ _ _

/-- `ℤᶜᵘⁿ_[p]` as a `ℤ_[p]`-algebra via `Zp_embd`. -/
noncomputable instance : Algebra ℤ_[p] ℤᶜᵘⁿ_[p] := (Zp_embd p).toAlgebra

theorem algebraMap_eq_Zp_embd : algebraMap ℤ_[p] ℤᶜᵘⁿ_[p] = Zp_embd p := rfl

/-- The image of `ℤ_[p]` has coefficients in every subfield of `𝔽ᵃ_[p]`. -/
theorem Zp_embd_mem_wittSubring (K : IntermediateField (ZMod p) 𝔽ᵃ_[p]) (a : ℤ_[p]) :
    Zp_embd p a ∈ wittSubring p K :=
  (mem_wittSubring_iff p).2 fun n => by
    rw [coeff_Zp_embd]
    exact K.algebraMap_mem _

theorem Zp_embd_mem_OQpUn (a : ℤ_[p]) : Zp_embd p a ∈ ℤᵘⁿ_[p] :=
  QpUn.map_fromPadicInt_mem_OQpUn p a

end OQpCUn

namespace QpCUn

/-- `QpCUn.Qp_embd` restricts to `Zp_embd` on `ℤ_[p]`. -/
theorem Qp_embd_algebraMap (a : ℤ_[p]) :
    QpCUn.Qp_embd (algebraMap ℤ_[p] ℚ_[p] a) =
      algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] (OQpCUn.Zp_embd p a) := by
  rw [QpCUn.Qp_embd, IsFractionRing.map, IsLocalization.map_eq]
  rfl

/-- The `ℤ_[p]`-algebra structure on `ℚᶜᵘⁿ_[p]` inherited from `ℤᶜᵘⁿ_[p]` (through the fraction
field) agrees with the one through `ℚ_[p]`. -/
theorem algebraMap_Zp_apply (a : ℤ_[p]) :
    algebraMap ℤ_[p] ℚᶜᵘⁿ_[p] a = QpCUn.Qp_embd (algebraMap ℤ_[p] ℚ_[p] a) := by
  rw [IsScalarTower.algebraMap_apply ℤ_[p] ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p], Qp_embd_algebraMap]
  rfl

instance : IsScalarTower ℤ_[p] ℚ_[p] ℚᶜᵘⁿ_[p] :=
  IsScalarTower.of_algebraMap_eq fun a => algebraMap_Zp_apply p a

/-! ### The Frobenius of `ℚᶜᵘⁿ_[p]` -/

theorem frobenius_injective :
    Function.Injective (WittVector.frobenius : ℤᶜᵘⁿ_[p] → ℤᶜᵘⁿ_[p]) :=
  (WittVector.frobenius_bijective p 𝔽ᵃ_[p]).injective

/-- The Witt vector Frobenius fixes `ℤ_[p] = W(𝔽_p)` pointwise. -/
theorem frobenius_Zp_embd (a : ℤ_[p]) :
    WittVector.frobenius (OQpCUn.Zp_embd p a) = OQpCUn.Zp_embd p a :=
  WittVector.ext fun n => by
    rw [coeff_frobenius_charP, OQpCUn.coeff_Zp_embd, ← map_pow, ZMod.pow_card]

/-- The Frobenius of `ℚᶜᵘⁿ_[p]`: the Witt vector Frobenius of `ℤᶜᵘⁿ_[p] = W(𝔽ᵃ_[p])` extended
to the fraction field. -/
noncomputable def frobenius : ℚᶜᵘⁿ_[p] →+* ℚᶜᵘⁿ_[p] :=
  IsFractionRing.lift (g := (algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p]).comp WittVector.frobenius)
    (by
      rw [RingHom.coe_comp]
      exact (IsFractionRing.injective ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p]).comp (frobenius_injective p))

theorem frobenius_algebraMap (a : ℤᶜᵘⁿ_[p]) :
    frobenius p (algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] a) =
      algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] (WittVector.frobenius a) :=
  IsFractionRing.lift_algebraMap _ _

theorem frobenius_injective' : Function.Injective (frobenius p) := (frobenius p).injective

/-- The Frobenius of `ℚᶜᵘⁿ_[p]` fixes `ℚ_[p]` pointwise. -/
theorem frobenius_Qp_embd (x : ℚ_[p]) : frobenius p (QpCUn.Qp_embd x) = QpCUn.Qp_embd x := by
  obtain ⟨a, b, -, rfl⟩ := IsFractionRing.div_surjective (A := ℤ_[p]) x
  rw [map_div₀, map_div₀, Qp_embd_algebraMap, Qp_embd_algebraMap, frobenius_algebraMap,
    frobenius_algebraMap, frobenius_Zp_embd, frobenius_Zp_embd]

/-- The Frobenius of `ℚᶜᵘⁿ_[p]` as a `ℚ_[p]`-algebra endomorphism. -/
noncomputable def frobeniusAlgHom : ℚᶜᵘⁿ_[p] →ₐ[ℚ_[p]] ℚᶜᵘⁿ_[p] :=
  { frobenius p with commutes' := frobenius_Qp_embd p }

@[simp]
theorem coe_frobeniusAlgHom : ⇑(frobeniusAlgHom p) = frobenius p := rfl

theorem iterate_frobenius_algebraMap (a : ℤᶜᵘⁿ_[p]) (m : ℕ) :
    (frobenius p)^[m] (algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] a) =
      algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] (WittVector.frobenius^[m] a) := by
  induction m with
  | zero => rfl
  | succ m ih => rw [Function.iterate_succ_apply', ih, frobenius_algebraMap,
      Function.iterate_succ_apply']

theorem iterate_frobenius_div (x y : ℚᶜᵘⁿ_[p]) (m : ℕ) :
    (frobenius p)^[m] (x / y) = (frobenius p)^[m] x / (frobenius p)^[m] y := by
  induction m with
  | zero => rfl
  | succ m ih => rw [Function.iterate_succ_apply', ih, map_div₀, Function.iterate_succ_apply',
      Function.iterate_succ_apply']

end QpCUn

/-! ### `ℤᵘⁿ_[p]` and `ℚᵘⁿ_[p]` as the Frobenius-periodic elements -/

theorem mem_OQpUn_of_iterate_frobenius_eq {c : ℤᶜᵘⁿ_[p]} {m : ℕ} (hm : 0 < m)
    (h : WittVector.frobenius^[m] c = c) : c ∈ ℤᵘⁿ_[p] :=
  (mem_OQpUn_iff_exists_pow_eq p).2 ⟨m, hm, fun n => by
    conv_rhs => rw [← h]
    rw [iterate_frobenius_coeff]⟩

theorem exists_iterate_frobenius_eq_of_mem_OQpUn {c : ℤᶜᵘⁿ_[p]} (hc : c ∈ ℤᵘⁿ_[p]) :
    ∃ m : ℕ, 0 < m ∧ WittVector.frobenius^[m] c = c := by
  obtain ⟨r, hr, h⟩ := (mem_OQpUn_iff_exists_pow_eq p).1 hc
  exact ⟨r, hr, WittVector.ext fun n => by rw [iterate_frobenius_coeff, h n]⟩

/-- `x ∈ ℚᵘⁿ_[p]` if and only if `x` is fixed by some positive power of the Frobenius of
`ℚᶜᵘⁿ_[p]`. -/
theorem mem_QpUn_iff_exists_iterate_frobenius_eq {x : ℚᶜᵘⁿ_[p]} :
    x ∈ ℚᵘⁿ_[p] ↔ ∃ m : ℕ, 0 < m ∧ (QpCUn.frobenius p)^[m] x = x := by
  constructor
  · intro hx
    obtain ⟨a, ha, b, hb, rfl⟩ := (QpUn.mem_iff p).1 hx
    obtain ⟨r, hr, hra⟩ := exists_iterate_frobenius_eq_of_mem_OQpUn p ha
    obtain ⟨s, hs, hsb⟩ := exists_iterate_frobenius_eq_of_mem_OQpUn p hb
    refine ⟨r * s, Nat.mul_pos hr hs, ?_⟩
    have hab : WittVector.frobenius^[r * s] a = a := by
      rw [Function.iterate_mul, Function.iterate_fixed hra]
    have hbb : WittVector.frobenius^[r * s] b = b := by
      rw [mul_comm, Function.iterate_mul, Function.iterate_fixed hsb]
    rw [QpCUn.iterate_frobenius_div, QpCUn.iterate_frobenius_algebraMap,
      QpCUn.iterate_frobenius_algebraMap, hab, hbb]
  · rintro ⟨m, hm, hx⟩
    obtain ⟨a, b, hb, rfl⟩ := IsFractionRing.div_surjective (A := ℤᶜᵘⁿ_[p]) x
    obtain ⟨k, u, rfl⟩ := IsDiscreteValuationRing.eq_unit_mul_pow_irreducible
      (nonZeroDivisors.ne_zero hb) (WittVector.irreducible p)
    have hinj := IsFractionRing.injective ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p]
    have hpk : algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] ((p : ℤᶜᵘⁿ_[p]) ^ k) ≠ 0 :=
      (map_ne_zero_iff _ hinj).2 (pow_ne_zero _ (WittVector.p_nonzero p _))
    have hu : algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] (u : ℤᶜᵘⁿ_[p]) ≠ 0 :=
      (map_ne_zero_iff _ hinj).2 u.ne_zero
    -- rewrite `x = c / p ^ k` with `c = a * u⁻¹`
    have heq : algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] a /
        algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] (↑u * (p : ℤᶜᵘⁿ_[p]) ^ k) =
        algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] (a * ↑u⁻¹) /
          algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] ((p : ℤᶜᵘⁿ_[p]) ^ k) := by
      rw [map_mul, map_mul, map_units_inv]
      field_simp
    rw [heq] at hx ⊢
    -- Frobenius fixes `p ^ k`, so it fixes `c`
    have hfp : WittVector.frobenius^[m] ((p : ℤᶜᵘⁿ_[p]) ^ k) = (p : ℤᶜᵘⁿ_[p]) ^ k :=
      Function.iterate_fixed (by rw [map_pow, map_natCast]) m
    rw [QpCUn.iterate_frobenius_div, QpCUn.iterate_frobenius_algebraMap,
      QpCUn.iterate_frobenius_algebraMap, hfp, div_left_inj' hpk] at hx
    have hc : a * ↑u⁻¹ ∈ ℤᵘⁿ_[p] := mem_OQpUn_of_iterate_frobenius_eq p hm (hinj hx)
    exact div_mem (QpUn.algebraMap_mem p hc)
      (QpUn.algebraMap_mem p (pow_mem (natCast_mem _ p) k))

/-! ### `ℚᵘⁿ_[p]` is the algebraic closure of `ℚ_[p]` in `ℚᶜᵘⁿ_[p]` -/

/-- **Maximality.** Every element of `ℚᶜᵘⁿ_[p]` that is algebraic over `ℚ_[p]` lies in
`ℚᵘⁿ_[p]`: the Frobenius orbit of such an element consists of roots of a fixed non-zero
polynomial, hence is finite, so the element is Frobenius-periodic. -/
theorem mem_QpUn_of_isAlgebraic {x : ℚᶜᵘⁿ_[p]} (hx : IsAlgebraic ℚ_[p] x) : x ∈ ℚᵘⁿ_[p] := by
  obtain ⟨P, hP0, hPx⟩ := hx
  set σ := QpCUn.frobeniusAlgHom p with hσ
  -- the roots of `P` in `ℚᶜᵘⁿ_[p]` form a finite set
  have hfin : {y : ℚᶜᵘⁿ_[p] | Polynomial.aeval y P = 0}.Finite := by
    have hne : P.map (algebraMap ℚ_[p] ℚᶜᵘⁿ_[p]) ≠ 0 :=
      (Polynomial.map_ne_zero_iff (algebraMap ℚ_[p] ℚᶜᵘⁿ_[p]).injective).2 hP0
    refine (Polynomial.finite_setOfPred_isRoot hne).subset fun y hy => ?_
    simpa [Polynomial.IsRoot.def, Polynomial.eval_map, Polynomial.aeval_def] using hy
  -- the Frobenius orbit of `x` consists of roots of `P`
  have horb : ∀ k : ℕ, (⇑σ)^[k] x ∈ {y : ℚᶜᵘⁿ_[p] | Polynomial.aeval y P = 0} := by
    intro k
    induction k with
    | zero => exact hPx
    | succ k ih =>
      simp only [Set.mem_ofPred_eq] at ih ⊢
      rw [Function.iterate_succ_apply', Polynomial.aeval_algHom_apply, ih, map_zero]
  -- pigeonhole: two iterates coincide
  have : Finite {y : ℚᶜᵘⁿ_[p] | Polynomial.aeval y P = 0} := hfin.to_subtype
  obtain ⟨k, l, hkl, hk⟩ := Finite.exists_ne_map_eq_of_infinite
    (fun k : ℕ => (⟨(⇑σ)^[k] x, horb k⟩ : {y : ℚᶜᵘⁿ_[p] | Polynomial.aeval y P = 0}))
  simp only [Subtype.mk.injEq] at hk
  -- reduce to `k < l`
  wlog hlt : k < l generalizing k l
  · exact this l k hkl.symm hk.symm (lt_of_le_of_ne (not_lt.1 hlt) hkl.symm)
  have hσinj : Function.Injective ⇑σ := QpCUn.frobenius_injective' p
  refine (mem_QpUn_iff_exists_iterate_frobenius_eq p).2 ⟨l - k, Nat.sub_pos_of_lt hlt, ?_⟩
  apply hσinj.iterate k
  change (⇑σ)^[k] ((⇑σ)^[l - k] x) = (⇑σ)^[k] x
  rw [← Function.iterate_add_apply, Nat.add_sub_cancel' hlt.le, ← hk]

/-! ### `ℤᵘⁿ_[p]` and its finite layers as `ℤ_[p]`-algebras -/

/-- `W(K) ⊆ ℤᶜᵘⁿ_[p]` as a `ℤ_[p]`-algebra, via `OQpCUn.Zp_embd`. -/
noncomputable instance (K : IntermediateField (ZMod p) 𝔽ᵃ_[p]) : Algebra ℤ_[p] (wittSubring p K) :=
  ((OQpCUn.Zp_embd p).codRestrict (wittSubring p K)
    (OQpCUn.Zp_embd_mem_wittSubring p K)).toAlgebra

instance (K : IntermediateField (ZMod p) 𝔽ᵃ_[p]) :
    IsScalarTower ℤ_[p] (wittSubring p K) ℤᶜᵘⁿ_[p] :=
  IsScalarTower.of_algebraMap_eq fun _ => rfl

/-- `ℤᵘⁿ_[p]` as a `ℤ_[p]`-algebra, via `OQpCUn.Zp_embd`. -/
noncomputable instance : Algebra ℤ_[p] ℤᵘⁿ_[p] :=
  ((OQpCUn.Zp_embd p).codRestrict ℤᵘⁿ_[p] (OQpCUn.Zp_embd_mem_OQpUn p)).toAlgebra

instance : IsScalarTower ℤ_[p] ℤᵘⁿ_[p] ℤᶜᵘⁿ_[p] :=
  IsScalarTower.of_algebraMap_eq fun _ => rfl

theorem coe_smul_Zp_wittSubring (K : IntermediateField (ZMod p) 𝔽ᵃ_[p]) (c : ℤ_[p])
    (x : wittSubring p K) : ((c • x : wittSubring p K) : ℤᶜᵘⁿ_[p]) = c • (x : ℤᶜᵘⁿ_[p]) := by
  rw [Algebra.smul_def, Algebra.smul_def, Subring.coe_mul]
  rfl

theorem coe_smul_Zp_OQpUn (c : ℤ_[p]) (x : ℤᵘⁿ_[p]) :
    ((c • x : ℤᵘⁿ_[p]) : ℤᶜᵘⁿ_[p]) = c • (x : ℤᶜᵘⁿ_[p]) := by
  rw [Algebra.smul_def, Algebra.smul_def, Subring.coe_mul]
  rfl

/-- Elements of `W(K)` with non-zero constant coefficient are units of `W(K)`. -/
theorem isUnit_wittSubring_of_coeff_zero_ne_zero (K : IntermediateField (ZMod p) 𝔽ᵃ_[p])
    (x : wittSubring p K) (hx : (x : ℤᶜᵘⁿ_[p]).coeff 0 ≠ 0) : IsUnit x := by
  obtain ⟨y, hy⟩ := x.2
  have hy0 : y.coeff 0 ≠ 0 := by
    intro h
    apply hx
    rw [← hy, map_coeff, h, map_zero]
  let f : WittVector p K →+* wittSubring p K :=
    (WittVector.map (K.val : K →+* 𝔽ᵃ_[p])).codRestrict (wittSubring p K) fun z => ⟨z, rfl⟩
  have hfy : f y = x := Subtype.ext hy
  rw [← hfy]
  exact (WittVector.isUnit_of_coeff_zero_ne_zero y hy0).map f

/-- Elements of `ℤᵘⁿ_[p]` with non-zero constant coefficient are units of `ℤᵘⁿ_[p]`. -/
theorem OQpUn.isUnit_of_coeff_zero_ne_zero (x : ℤᵘⁿ_[p]) (hx : (x : ℤᶜᵘⁿ_[p]).coeff 0 ≠ 0) :
    IsUnit x := by
  obtain ⟨K, hK, hxK⟩ := x.2
  have hle : wittSubring p K ≤ ℤᵘⁿ_[p] := wittSubring_le_OQpUn p K
  have hmem : (x : ℤᶜᵘⁿ_[p]) ∈ wittSubring p K := (mem_wittSubring_iff p).2 hxK
  have := (isUnit_wittSubring_of_coeff_zero_ne_zero p K ⟨x, hmem⟩ hx).map (Subring.inclusion hle)
  rwa [show Subring.inclusion hle ⟨x, hmem⟩ = x from Subtype.ext rfl] at this

/-- `ℤᵘⁿ_[p]` is a local ring: its non-units are the elements with zero constant coefficient. -/
instance : IsLocalRing ℤᵘⁿ_[p] := by
  refine IsLocalRing.of_isUnit_or_isUnit_one_sub_self fun x => ?_
  by_cases h : (x : ℤᶜᵘⁿ_[p]).coeff 0 = 0
  · right
    refine OQpUn.isUnit_of_coeff_zero_ne_zero p _ ?_
    rw [AddSubgroupClass.coe_sub, Subring.coe_one, ← constantCoeff_apply, map_sub, map_one,
      constantCoeff_apply, h, sub_zero]
    exact one_ne_zero
  · exact Or.inl (OQpUn.isUnit_of_coeff_zero_ne_zero p x h)

/-! ### Finite generation of the layers `W(𝔽_{p^r})` by Teichmüller lifts -/

/-- The inclusion `ℤ_[p] → ℚᶜᵘⁿ_[p]` is continuous. -/
theorem QpCUn.continuous_algebraMap_Zp : Continuous (algebraMap ℤ_[p] ℚᶜᵘⁿ_[p]) := by
  refine continuous_of_continuousAt_zero (algebraMap ℤ_[p] ℚᶜᵘⁿ_[p]) ?_
  rw [ContinuousAt, map_zero, Filter.tendsto_def]
  intro U hU
  obtain ⟨γ, hγ⟩ := Valued.mem_nhds.1 hU
  set g : WithZero (Multiplicative ℤ) := MonoidWithZeroHom.ValueGroup₀.embedding γ.1 with hg
  have hg0 : g ≠ 0 := MonoidWithZeroHom.ValueGroup₀.embedding_unit_ne_zero γ
  set N : ℕ := (1 - g.log).toNat with hNdef
  have hN : WithZero.exp (-(N : ℤ)) < g := by
    rw [← WithZero.lt_log_iff_exp_lt hg0]
    by_cases hpos : 1 - g.log ≥ 0
    · rw [hNdef, Int.toNat_of_nonneg hpos]; omega
    · rw [hNdef, Int.toNat_of_nonpos (le_of_lt (by omega))]; push_cast; omega
  have hpos : (0 : ℝ) < (p : ℝ) ^ (-(N : ℤ)) :=
    zpow_pos (by exact_mod_cast (Fact.out : Nat.Prime p).pos) _
  refine Filter.mem_of_superset (Metric.closedBall_mem_nhds (0 : ℤ_[p]) hpos) fun c hc => ?_
  rw [Set.mem_preimage]
  refine hγ ?_
  rw [Set.mem_ofPred_eq, sub_zero, Valuation.restrict_lt_iff_lt_embedding, ← hg]
  rw [mem_closedBall_zero_iff, PadicInt.norm_le_pow_iff_mem_span_pow] at hc
  refine lt_of_le_of_lt ?_ hN
  rw [IsScalarTower.algebraMap_apply ℤ_[p] ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p]]
  refine QpUn.valued_algebraMap_le_of_mem_span p ?_
  rw [Ideal.mem_span_singleton] at hc ⊢
  obtain ⟨d, hd⟩ := hc
  exact ⟨algebraMap ℤ_[p] ℤᶜᵘⁿ_[p] d, by rw [hd, map_mul, map_pow, map_natCast]⟩

/-- Truncating the Teichmüller expansion: every `y ∈ W(K)`, `K` a finite subfield of `𝔽ᵃ_[p]`,
is congruent modulo `p ^ N` to a `ℤ_[p]`-combination of Teichmüller lifts of elements of `K`. -/
theorem exists_sum_teichmuller_sub_mem_span (K : IntermediateField (ZMod p) 𝔽ᵃ_[p])
    [FiniteDimensional (ZMod p) K] [Fintype K] (y : WittVector p K) (N : ℕ) :
    ∃ c : K → ℤ_[p], WittVector.map (K.val : K →+* 𝔽ᵃ_[p]) y -
      ∑ α, algebraMap ℤ_[p] ℤᶜᵘⁿ_[p] (c α) * teichmuller p (α : 𝔽ᵃ_[p]) ∈
        Ideal.span {(p : ℤᶜᵘⁿ_[p]) ^ N} := by
  classical
  have : PerfectField K := PerfectField.ofFinite
  have : PerfectRing K p := PerfectField.toPerfectRing p
  induction N generalizing y with
  | zero =>
    refine ⟨0, ?_⟩
    rw [pow_zero, Ideal.span_singleton_one]
    exact Submodule.mem_top
  | succ N ih =>
    set y₀ := y.coeff 0 with hy₀
    have hmem : y - teichmuller p y₀ ∈ Ideal.span {(p : WittVector p K)} := by
      rw [mem_span_p_iff_coeff_zero_eq_zero, ← constantCoeff_apply, map_sub, constantCoeff_apply,
        constantCoeff_apply, teichmuller_coeff_zero, sub_self]
    obtain ⟨y', hy'⟩ := Ideal.mem_span_singleton.1 hmem
    obtain ⟨c', hc'⟩ := ih y'
    refine ⟨fun α => (if α = y₀ then 1 else 0) + p * c' α, ?_⟩
    have hy : y = teichmuller p y₀ + p * y' := by rw [← hy']; ring
    have hsum : ∑ α : K, algebraMap ℤ_[p] ℤᶜᵘⁿ_[p] ((if α = y₀ then 1 else 0) + p * c' α) *
        teichmuller p (α : 𝔽ᵃ_[p]) =
        teichmuller p (y₀ : 𝔽ᵃ_[p]) +
          (p : ℤᶜᵘⁿ_[p]) *
            ∑ α : K, algebraMap ℤ_[p] ℤᶜᵘⁿ_[p] (c' α) * teichmuller p (α : 𝔽ᵃ_[p]) := by
      simp only [map_add, map_mul, map_natCast, apply_ite (algebraMap ℤ_[p] ℤᶜᵘⁿ_[p]), map_one,
        map_zero, add_mul, Finset.sum_add_distrib, ite_mul, one_mul, zero_mul, Finset.sum_ite_eq',
        Finset.mem_univ, if_true, Finset.mul_sum, mul_assoc]
    rw [hsum, hy, map_add, map_mul, map_natCast, map_teichmuller]
    have hcast : (K.val : K →+* 𝔽ᵃ_[p]) y₀ = (y₀ : 𝔽ᵃ_[p]) := rfl
    rw [hcast]
    have : teichmuller p (y₀ : 𝔽ᵃ_[p]) + (p : ℤᶜᵘⁿ_[p]) * WittVector.map (K.val : K →+* 𝔽ᵃ_[p]) y' -
        (teichmuller p (y₀ : 𝔽ᵃ_[p]) +
          (p : ℤᶜᵘⁿ_[p]) * ∑ α : K, algebraMap ℤ_[p] ℤᶜᵘⁿ_[p] (c' α) * teichmuller p (α : 𝔽ᵃ_[p])) =
        (p : ℤᶜᵘⁿ_[p]) * (WittVector.map (K.val : K →+* 𝔽ᵃ_[p]) y' -
          ∑ α : K, algebraMap ℤ_[p] ℤᶜᵘⁿ_[p] (c' α) * teichmuller p (α : 𝔽ᵃ_[p])) := by ring
    rw [this, Ideal.mem_span_singleton, pow_succ']
    exact mul_dvd_mul_left _ (Ideal.mem_span_singleton.1 hc')

/-- **Finite generation of `W(𝔽_{p^r})` over `ℤ_[p]`**: every element of `W(K) ⊆ ℤᶜᵘⁿ_[p]`, `K`
a finite subfield of `𝔽ᵃ_[p]`, is a `ℤ_[p]`-linear combination of the Teichmüller lifts of the
elements of `K`. The proof uses that `ℤ_[p]` is compact, so the set of such combinations is
closed in `ℚᶜᵘⁿ_[p]`, together with the `p`-adic approximation
`exists_sum_teichmuller_sub_mem_span`. -/
theorem exists_eq_sum_smul_teichmuller_of_mem_wittSubring (K : IntermediateField (ZMod p) 𝔽ᵃ_[p])
    [FiniteDimensional (ZMod p) K] [Fintype K] {x : ℤᶜᵘⁿ_[p]} (hx : x ∈ wittSubring p K) :
    ∃ c : K → ℤ_[p], x = ∑ α, c α • teichmuller p (α : 𝔽ᵃ_[p]) := by
  classical
  obtain ⟨y, rfl⟩ := hx
  set ι := algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] with hι
  let Φ : (K → ℤ_[p]) → ℚᶜᵘⁿ_[p] := fun c =>
    ∑ α, algebraMap ℤ_[p] ℚᶜᵘⁿ_[p] (c α) * ι (teichmuller p (α : 𝔽ᵃ_[p]))
  have hΦ : Continuous Φ :=
    continuous_finsetSum _ fun α _ =>
      ((QpCUn.continuous_algebraMap_Zp p).comp (continuous_apply α)).mul continuous_const
  have hclosed : IsClosed (Set.range Φ) := (isCompact_range hΦ).isClosed
  have hΦ_eq : ∀ c : K → ℤ_[p], Φ c =
      ι (∑ α, algebraMap ℤ_[p] ℤᶜᵘⁿ_[p] (c α) * teichmuller p (α : 𝔽ᵃ_[p])) := by
    intro c
    simp only [Φ, hι, map_sum, map_mul, IsScalarTower.algebraMap_apply ℤ_[p] ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p]]
  have hmem : ι (WittVector.map (K.val : K →+* 𝔽ᵃ_[p]) y) ∈ closure (Set.range Φ) := by
    rw [mem_closure_iff_nhds]
    intro t ht
    obtain ⟨γ, hγ⟩ := Valued.mem_nhds.1 ht
    set g : WithZero (Multiplicative ℤ) := MonoidWithZeroHom.ValueGroup₀.embedding γ.1 with hg
    have hg0 : g ≠ 0 := MonoidWithZeroHom.ValueGroup₀.embedding_unit_ne_zero γ
    set N : ℕ := (1 - g.log).toNat with hNdef
    have hN : WithZero.exp (-(N : ℤ)) < g := by
      rw [← WithZero.lt_log_iff_exp_lt hg0]
      by_cases hpos : 1 - g.log ≥ 0
      · rw [hNdef, Int.toNat_of_nonneg hpos]; omega
      · rw [hNdef, Int.toNat_of_nonpos (le_of_lt (by omega))]; push_cast; omega
    obtain ⟨c, hc⟩ := exists_sum_teichmuller_sub_mem_span p K y N
    refine ⟨Φ c, hγ ?_, ⟨c, rfl⟩⟩
    rw [Set.mem_ofPred_eq, Valuation.restrict_lt_iff_lt_embedding, ← hg, Valuation.map_sub_swap,
      hΦ_eq, ← map_sub]
    exact lt_of_le_of_lt (QpUn.valued_algebraMap_le_of_mem_span p hc) hN
  obtain ⟨c, hc⟩ := hclosed.closure_subset hmem
  refine ⟨c, IsFractionRing.injective ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] ?_⟩
  rw [← hc, hΦ_eq]
  simp only [Algebra.smul_def]
  rfl

/-- `W(K)` is a finite `ℤ_[p]`-module for every finite subfield `K ⊆ 𝔽ᵃ_[p]`. -/
instance wittSubring.instModuleFinite (K : IntermediateField (ZMod p) 𝔽ᵃ_[p])
    [FiniteDimensional (ZMod p) K] : Module.Finite ℤ_[p] (wittSubring p K) := by
  classical
  have : Finite K := Module.finite_of_finite (ZMod p)
  let _ : Fintype K := Fintype.ofFinite K
  let v : K → wittSubring p K := fun α =>
    ⟨teichmuller p (α : 𝔽ᵃ_[p]), (mem_wittSubring_iff p).2 fun n => by
      rcases n with _ | n
      · rw [teichmuller_coeff_zero]; exact α.2
      · rw [teichmuller_coeff_pos p _ _ n.succ_pos]; exact zero_mem _⟩
  refine Module.Finite.of_surjective (Fintype.linearCombination ℤ_[p] v) fun x => ?_
  obtain ⟨c, hc⟩ := exists_eq_sum_smul_teichmuller_of_mem_wittSubring p K x.2
  refine ⟨c, Subtype.ext ?_⟩
  rw [Fintype.linearCombination_apply, AddSubmonoidClass.coe_finsetSum, hc]
  simp only [coe_smul_Zp_wittSubring, v]

/-! ### `ℤᵘⁿ_[p]` is formally unramified over `ℤ_[p]` -/

/-- In a `ℤ_[p]`-subalgebra `B ⊆ ℤᶜᵘⁿ_[p]` in which elements with non-zero constant coefficient
are units, every `ℤ_[p]`-derivation kills the Teichmüller lift `t = [α]` of an element `α` of a
finite subfield `K`: `t ^ q = t` for `q = |K|`, so `(1 - q t ^ (q - 1)) • D t = 0`, and
`1 - q t ^ (q - 1)` has constant coefficient `1` (as `q = 0` in characteristic `p`). -/
theorem derivation_teichmuller_eq_zero {B : Subring ℤᶜᵘⁿ_[p]} [Algebra ℤ_[p] B]
    (hunit : ∀ b : B, (b : ℤᶜᵘⁿ_[p]).coeff 0 ≠ 0 → IsUnit b)
    {M : Type*} [AddCommGroup M] [Module B M] [Module ℤ_[p] M] [IsScalarTower ℤ_[p] B M]
    (D : Derivation ℤ_[p] B M) (K : IntermediateField (ZMod p) 𝔽ᵃ_[p])
    [FiniteDimensional (ZMod p) K] (α : K) (t : B)
    (ht : (t : ℤᶜᵘⁿ_[p]) = teichmuller p (α : 𝔽ᵃ_[p])) : D t = 0 := by
  classical
  have : Finite K := Module.finite_of_finite (ZMod p)
  let _ : Fintype K := Fintype.ofFinite K
  set q := Fintype.card K with hqdef
  obtain ⟨r, -, hq⟩ := FiniteField.card K p
  have hq0 : ((q : ℕ) : 𝔽ᵃ_[p]) = 0 := by
    rw [hqdef, hq]
    exact (CharP.cast_eq_zero_iff 𝔽ᵃ_[p] p _).2 (dvd_pow_self p r.ne_zero)
  have htq : t ^ q = t := by
    apply Subtype.ext
    rw [Subring.coe_pow, ht, ← map_pow, ← SubmonoidClass.coe_pow, FiniteField.pow_card]
  have hD : D t = (q : B) • (t ^ (q - 1) • D t) := by
    conv_lhs => rw [← htq]
    rw [Derivation.leibniz_pow, Nat.cast_smul_eq_nsmul]
  have hzero : (1 - (q : B) * t ^ (q - 1)) • D t = 0 := by
    rw [sub_smul, one_smul, mul_smul]
    exact sub_eq_zero.2 hD
  have hu : IsUnit (1 - (q : B) * t ^ (q - 1)) := by
    apply hunit
    rw [← constantCoeff_apply, AddSubgroupClass.coe_sub, Subring.coe_one, Subring.coe_mul,
      SubringClass.coe_natCast, Subring.coe_pow, ht, map_sub, map_one, map_mul, map_natCast,
      map_pow, constantCoeff_apply, teichmuller_coeff_zero, hq0, zero_mul, sub_zero]
    exact one_ne_zero
  exact hu.smul_eq_zero.1 hzero

/-- A `ℤ_[p]`-subalgebra `B ⊆ ℤᶜᵘⁿ_[p]` in which elements with non-zero constant coefficient are
units and which is `ℤ_[p]`-spanned by Teichmüller lifts of elements of finite subfields is
formally unramified over `ℤ_[p]`. -/
theorem formallyUnramified_of_forall_exists_sum {B : Subring ℤᶜᵘⁿ_[p]} [Algebra ℤ_[p] B]
    (hunit : ∀ b : B, (b : ℤᶜᵘⁿ_[p]).coeff 0 ≠ 0 → IsUnit b)
    (hgen : ∀ b : B, ∃ (K : IntermediateField (ZMod p) 𝔽ᵃ_[p]) (_ : FiniteDimensional (ZMod p) K)
      (_ : Fintype K) (c : K → ℤ_[p]) (t : K → B),
      (∀ α, (t α : ℤᶜᵘⁿ_[p]) = teichmuller p (α : 𝔽ᵃ_[p])) ∧ b = ∑ α, c α • t α) :
    Algebra.FormallyUnramified ℤ_[p] B := by
  constructor
  rw [subsingleton_iff_forall_eq 0]
  intro ω
  have hω : ω ∈ Submodule.span B (Set.range (KaehlerDifferential.D ℤ_[p] B)) := by
    rw [KaehlerDifferential.span_range_derivation]; exact Submodule.mem_top
  suffices h : Submodule.span B (Set.range (KaehlerDifferential.D ℤ_[p] B)) ≤ ⊥ from
    (Submodule.mem_bot B).1 (h hω)
  rw [Submodule.span_le]
  rintro _ ⟨b, rfl⟩
  rw [SetLike.mem_coe, Submodule.mem_bot]
  obtain ⟨K, hK, hF, c, t, ht, hb⟩ := hgen b
  rw [hb, ← Derivation.coeFn_coe, map_sum]
  refine Finset.sum_eq_zero fun α _ => ?_
  rw [Derivation.coeFn_coe, Derivation.map_smul,
    derivation_teichmuller_eq_zero p hunit (KaehlerDifferential.D ℤ_[p] B) K α (t α) (ht α),
    smul_zero]

/-- **Unramifiedness of the finite layers.** `W(K)`, `K ⊆ 𝔽ᵃ_[p]` a finite subfield, is formally
unramified over `ℤ_[p]`. -/
instance wittSubring.instFormallyUnramified (K : IntermediateField (ZMod p) 𝔽ᵃ_[p])
    [FiniteDimensional (ZMod p) K] : Algebra.FormallyUnramified ℤ_[p] (wittSubring p K) := by
  classical
  have : Finite K := Module.finite_of_finite (ZMod p)
  let _ : Fintype K := Fintype.ofFinite K
  refine formallyUnramified_of_forall_exists_sum p
    (isUnit_wittSubring_of_coeff_zero_ne_zero p K) fun b => ?_
  obtain ⟨c, hc⟩ := exists_eq_sum_smul_teichmuller_of_mem_wittSubring p K b.2
  refine ⟨K, inferInstance, inferInstance, c, fun α =>
    ⟨teichmuller p (α : 𝔽ᵃ_[p]), (mem_wittSubring_iff p).2 fun n => by
      rcases n with _ | n
      · rw [teichmuller_coeff_zero]; exact α.2
      · rw [teichmuller_coeff_pos p _ _ n.succ_pos]; exact zero_mem _⟩, fun α => rfl, ?_⟩
  apply Subtype.ext
  rw [AddSubmonoidClass.coe_finsetSum, hc]
  simp only [coe_smul_Zp_wittSubring]

/-- **Unramifiedness of the finite layers.** `W(K)`, `K ⊆ 𝔽ᵃ_[p]` a finite subfield, is an
unramified `ℤ_[p]`-algebra in the sense of `Algebra.Unramified` (formally unramified and of
finite type). -/
instance wittSubring.instUnramified (K : IntermediateField (ZMod p) 𝔽ᵃ_[p])
    [FiniteDimensional (ZMod p) K] : Algebra.Unramified ℤ_[p] (wittSubring p K) where

/-- **`ℚᵘⁿ_[p]` is unramified over `ℚ_[p]`**: its ring of integers `ℤᵘⁿ_[p]` is formally
unramified over `ℤ_[p]`, i.e. `Ω[ℤᵘⁿ_[p]⁄ℤ_[p]] = 0`. (The stronger `Algebra.Unramified` cannot
hold, since `ℤᵘⁿ_[p]` is not of finite type over `ℤ_[p]`; it holds for every finite layer
`W(𝔽_{p^r})`, see `wittSubring.instUnramified`.) -/
instance OQpUn.instFormallyUnramified : Algebra.FormallyUnramified ℤ_[p] ℤᵘⁿ_[p] := by
  classical
  refine formallyUnramified_of_forall_exists_sum p (OQpUn.isUnit_of_coeff_zero_ne_zero p)
    fun b => ?_
  obtain ⟨K, hK, hb⟩ := b.2
  have : Finite K := Module.finite_of_finite (ZMod p)
  let _ : Fintype K := Fintype.ofFinite K
  obtain ⟨c, hc⟩ :=
    exists_eq_sum_smul_teichmuller_of_mem_wittSubring p K ((mem_wittSubring_iff p).2 hb)
  refine ⟨K, hK, inferInstance, c, fun α => ⟨teichmuller p (α : 𝔽ᵃ_[p]), teichmuller_mem_OQpUn p _⟩,
    fun α => rfl, ?_⟩
  apply Subtype.ext
  rw [AddSubmonoidClass.coe_finsetSum, hc]
  simp only [coe_smul_Zp_OQpUn]


/-! ### Auxiliary: adic completeness of finite free modules -/

section AdicComplete

variable {R : Type*} [CommRing R] (I : Ideal R)

theorem mem_smul_top_pi_iff {ι : Type*} [Finite ι] (J : Ideal R) (x : ι → R) :
    x ∈ (J • ⊤ : Submodule R (ι → R)) ↔ ∀ i, x i ∈ J := by
  classical
  cases nonempty_fintype ι
  constructor
  · intro h i
    have := Submodule.mem_map_of_mem (f := (LinearMap.proj i : (ι → R) →ₗ[R] R)) h
    rwa [Submodule.map_smul'', Submodule.map_top,
      LinearMap.range_eq_top.2 (Function.surjective_eval i), Ideal.smul_eq_mul, Ideal.mul_top]
      at this
  · intro h
    rw [← Finset.univ_sum_single x]
    refine Submodule.sum_mem _ fun i _ => ?_
    rw [← mul_one (x i), ← smul_eq_mul, Pi.single_smul']
    exact Submodule.smul_mem_smul (h i) Submodule.mem_top

/-- A finite power of an `I`-adically precomplete ring is precomplete. -/
theorem IsPrecomplete.pi_of_finite {ι : Type*} [Finite ι] [IsPrecomplete I R] :
    IsPrecomplete I (ι → R) := by
  refine ⟨fun f hf => ?_⟩
  have hcoord : ∀ i : ι, ∃ L : R, ∀ n, f n i ≡ L [SMOD (I ^ n • ⊤ : Submodule R R)] := by
    intro i
    refine IsPrecomplete.prec ‹_› fun {m n} hmn => ?_
    rw [SModEq.sub_mem, Ideal.smul_eq_mul, Ideal.mul_top]
    have := hf hmn
    rw [SModEq.sub_mem, mem_smul_top_pi_iff] at this
    exact this i
  choose L hL using hcoord
  refine ⟨L, fun n => ?_⟩
  rw [SModEq.sub_mem, mem_smul_top_pi_iff]
  intro i
  have := hL i n
  rwa [SModEq.sub_mem, Ideal.smul_eq_mul, Ideal.mul_top] at this

/-- Precompleteness transports along linear equivalences. -/
theorem IsPrecomplete.of_linearEquiv {M N : Type*} [AddCommGroup M] [Module R M]
    [AddCommGroup N] [Module R N] (e : M ≃ₗ[R] N) [IsPrecomplete I M] : IsPrecomplete I N := by
  refine ⟨fun f hf => ?_⟩
  have hmap : ∀ n : ℕ,
      Submodule.map (e.symm : N →ₗ[R] M) (I ^ n • ⊤ : Submodule R N) = I ^ n • ⊤ := by
    intro n
    rw [Submodule.map_smul'', Submodule.map_top, LinearEquiv.range]
  have hmap' : ∀ n : ℕ,
      Submodule.map (e : M →ₗ[R] N) (I ^ n • ⊤ : Submodule R M) = I ^ n • ⊤ := by
    intro n
    rw [Submodule.map_smul'', Submodule.map_top, LinearEquiv.range]
  have hf' : ∀ {m n : ℕ}, m ≤ n →
      e.symm (f m) ≡ e.symm (f n) [SMOD (I ^ m • ⊤ : Submodule R M)] := by
    intro m n hmn
    have := (hf hmn).map (e.symm : N →ₗ[R] M)
    rwa [hmap, LinearEquiv.coe_coe] at this
  obtain ⟨L, hL⟩ := IsPrecomplete.prec ‹_› hf'
  refine ⟨e L, fun n => ?_⟩
  have := (hL n).map (e : M →ₗ[R] N)
  rwa [hmap', LinearEquiv.coe_coe, e.apply_symm_apply] at this

end AdicComplete

/-! ### `ℚᵘⁿ_[p]` contains every unramified extension of `ℚ_[p]` -/

section Maximality

open IsLocalRing Polynomial

/-- `𝔽_{p^N} ⊆ 𝔽ᵃ_[p]` has `p ^ N` elements. -/
theorem card_frobeniusFixed {N : ℕ} (hN : 0 < N) : Nat.card (frobeniusFixed p N) = p ^ N := by
  have hp1 : 1 < p := (Fact.out : Nat.Prime p).one_lt
  have hsep : (X ^ p ^ N - X : Polynomial (ZMod p)).Separable :=
    galois_poly_separable p (p ^ N) (dvd_pow_self p hN.ne')
  have hsplit := IsAlgClosed.splits
    ((X ^ p ^ N - X : Polynomial (ZMod p)).map (algebraMap (ZMod p) 𝔽ᵃ_[p]))
  have h1 := Polynomial.card_rootSet_eq_natDegree hsep hsplit
  rw [FiniteField.X_pow_card_pow_sub_X_natDegree_eq (ZMod p) hN.ne' hp1, Fintype.card_eq_nat_card]
    at h1
  rw [← h1]
  refine Nat.card_congr (Equiv.subtypeEquivRight fun a => ?_)
  rw [Polynomial.mem_rootSet, mem_frobeniusFixed_iff]
  simp only [FiniteField.X_pow_card_pow_sub_X_ne_zero (ZMod p) hN.ne' hp1, ne_eq,
    not_false_eq_true, true_and, map_sub, Polynomial.aeval_X_pow, Polynomial.aeval_X, sub_eq_zero]

/-- The Teichmüller lift of `α ∈ 𝔽_{p^N}`, viewed in `ℚᵘⁿ_[p]`. -/
noncomputable def QpUn.teichmullerRoot (N : ℕ) (α : frobeniusFixed p N) : ℚᵘⁿ_[p] :=
  ⟨algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] (teichmuller p (α : 𝔽ᵃ_[p])),
    QpUn.algebraMap_mem p (teichmuller_mem_OQpUn p _)⟩

theorem QpUn.teichmullerRoot_injective (N : ℕ) :
    Function.Injective (QpUn.teichmullerRoot p N) := by
  intro α β h
  have := congrArg Subtype.val h
  exact Subtype.ext
    (injective_teichmuller p (IsFractionRing.injective ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] this))

theorem QpUn.teichmullerRoot_pow (N : ℕ) (α : frobeniusFixed p N) :
    QpUn.teichmullerRoot p N α ^ p ^ N = QpUn.teichmullerRoot p N α := by
  apply Subtype.ext
  rw [SubmonoidClass.coe_pow]
  change algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] (teichmuller p (α : 𝔽ᵃ_[p])) ^ p ^ N =
    algebraMap ℤᶜᵘⁿ_[p] ℚᶜᵘⁿ_[p] (teichmuller p (α : 𝔽ᵃ_[p]))
  rw [← map_pow, ← map_pow, (mem_frobeniusFixed_iff p).1 α.2]

/-- `X ^ (p ^ N) - X` splits over `ℚᵘⁿ_[p]` for `N ≥ 1`: its `p ^ N` roots are the Teichmüller
lifts of the elements of `𝔽_{p^N} ⊆ 𝔽ᵃ_[p]`. -/
theorem QpUn.splits_X_pow_sub_X {N : ℕ} (hN : 0 < N) :
    (X ^ p ^ N - X : Polynomial ℚᵘⁿ_[p]).Splits := by
  classical
  have hp1 : 1 < p := (Fact.out : Nat.Prime p).one_lt
  have hne : (X ^ p ^ N - X : Polynomial ℚᵘⁿ_[p]) ≠ 0 :=
    FiniteField.X_pow_card_pow_sub_X_ne_zero ℚᵘⁿ_[p] hN.ne' hp1
  have hdeg : (X ^ p ^ N - X : Polynomial ℚᵘⁿ_[p]).natDegree = p ^ N :=
    FiniteField.X_pow_card_pow_sub_X_natDegree_eq ℚᵘⁿ_[p] hN.ne' hp1
  rw [Polynomial.splits_iff_card_roots]
  refine le_antisymm (Polynomial.card_roots' _) ?_
  rw [hdeg]
  have : Finite (frobeniusFixed p N) := finite_frobeniusFixed p hN
  let _ : Fintype (frobeniusFixed p N) := Fintype.ofFinite _
  have hroot : ∀ α, QpUn.teichmullerRoot p N α ∈ (X ^ p ^ N - X : Polynomial ℚᵘⁿ_[p]).roots := by
    intro α
    rw [Polynomial.mem_roots hne, Polynomial.IsRoot.def, Polynomial.eval_sub,
      Polynomial.eval_pow, Polynomial.eval_X, sub_eq_zero]
    exact QpUn.teichmullerRoot_pow p N α
  calc p ^ N = Nat.card (frobeniusFixed p N) := (card_frobeniusFixed p hN).symm
    _ = (Finset.univ.image (QpUn.teichmullerRoot p N)).card := by
        rw [Finset.card_image_of_injective _ (QpUn.teichmullerRoot_injective p N),
          Finset.card_univ, Nat.card_eq_fintype_card]
    _ = (Finset.univ.image (QpUn.teichmullerRoot p N)).val.card := (Finset.card_val _).symm
    _ ≤ (X ^ p ^ N - X : Polynomial ℚᵘⁿ_[p]).roots.card := by
        refine Multiset.card_le_card ((Multiset.le_iff_subset (Finset.nodup _)).2 fun x hx => ?_)
        rw [Finset.mem_val, Finset.mem_image] at hx
        obtain ⟨α, -, rfl⟩ := hx
        exact hroot α

variable (L : Type*) [Field L] [Algebra ℚ_[p] L] [FiniteDimensional ℚ_[p] L]
  [Algebra ℤ_[p] L] [IsScalarTower ℤ_[p] ℚ_[p] L]

omit [FiniteDimensional ℚ_[p] L] in
theorem algebraMap_Zp_injective : Function.Injective (algebraMap ℤ_[p] L) := by
  rw [IsScalarTower.algebraMap_eq ℤ_[p] ℚ_[p] L]
  exact (algebraMap ℚ_[p] L).injective.comp (IsFractionRing.injective ℤ_[p] ℚ_[p])

omit [FiniteDimensional ℚ_[p] L] in
/-- `ℤ_[p] → 𝒪_L` is injective, where `𝒪_L = integralClosure ℤ_[p] L`. -/
theorem algebraMap_Zp_integralClosure_injective :
    Function.Injective (algebraMap ℤ_[p] (integralClosure ℤ_[p] L)) := by
  have h := algebraMap_Zp_injective p L
  rw [IsScalarTower.algebraMap_eq ℤ_[p] (integralClosure ℤ_[p] L) L, RingHom.coe_comp] at h
  exact h.of_comp

/-- The ring of integers `𝒪_L = integralClosure ℤ_[p] L` of a finite extension `L/ℚ_[p]` is
`p`-adically complete: it is a finite free `ℤ_[p]`-module. -/
theorem integralClosure.isAdicComplete_map_maximalIdeal :
    IsAdicComplete ((maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (integralClosure ℤ_[p] L)))
      (integralClosure ℤ_[p] L) := by
  have : Module.IsTorsionFree ℤ_[p] L :=
    Module.isTorsionFree_iff_algebraMap_injective.2 (algebraMap_Zp_injective p L)
  have : Module.Finite ℤ_[p] (integralClosure ℤ_[p] L) :=
    IsIntegralClosure.finite ℤ_[p] ℚ_[p] L (integralClosure ℤ_[p] L)
  have : Module.Free ℤ_[p] (integralClosure ℤ_[p] L) :=
    IsIntegralClosure.module_free ℤ_[p] ℚ_[p] L (integralClosure ℤ_[p] L)
  let b := Module.Free.chooseBasis ℤ_[p] (integralClosure ℤ_[p] L)
  have : IsPrecomplete (maximalIdeal ℤ_[p]) (integralClosure ℤ_[p] L) :=
    have := IsPrecomplete.pi_of_finite (maximalIdeal ℤ_[p])
      (ι := Module.Free.ChooseBasisIndex ℤ_[p] (integralClosure ℤ_[p] L))
    IsPrecomplete.of_linearEquiv (maximalIdeal ℤ_[p]) b.equivFun.symm
  have : IsHausdorff (maximalIdeal ℤ_[p]) (integralClosure ℤ_[p] L) :=
    IsHausdorff.of_isLocalRing _ _ (maximalIdeal.isMaximal ℤ_[p]).ne_top
  have : IsPrecomplete ((maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (integralClosure ℤ_[p] L)))
      (integralClosure ℤ_[p] L) := IsPrecomplete.map_algebraMap_iff.2 ‹_›
  have : IsHausdorff ((maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (integralClosure ℤ_[p] L)))
      (integralClosure ℤ_[p] L) := IsHausdorff.map_algebraMap_iff.2 ‹_›
  exact ⟨⟩

omit [Algebra ℚ_[p] L] [FiniteDimensional ℚ_[p] L] [IsScalarTower ℤ_[p] ℚ_[p] L] in
/-- `p` lies in `p 𝒪_L`. -/
theorem natCast_p_mem_map_maximalIdeal :
    ((p : ℕ) : integralClosure ℤ_[p] L) ∈
      (maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (integralClosure ℤ_[p] L)) := by
  have hp : ((p : ℕ) : ℤ_[p]) ∈ maximalIdeal ℤ_[p] := by
    rw [PadicInt.maximalIdeal_eq_span_p]
    exact Ideal.mem_span_singleton_self _
  have := Ideal.mem_map_of_mem (algebraMap ℤ_[p] (integralClosure ℤ_[p] L)) hp
  rwa [map_natCast] at this

/-- For an unramified extension, some power of Frobenius is the identity on the residue algebra
`𝒪_L / p 𝒪_L`: `x ^ (p ^ N) = x` for all `x` and a single `N ≥ 1`. Indeed `𝒪_L / p 𝒪_L` is a
finite reduced `𝔽_p`-algebra, so its Frobenius is a permutation. -/
theorem exists_pow_pow_eq_self_quotient
    [Algebra.FormallyUnramified ℤ_[p] (integralClosure ℤ_[p] L)] :
    ∃ N : ℕ, 0 < N ∧ ∀ x : (integralClosure ℤ_[p] L) ⧸
      (maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (integralClosure ℤ_[p] L)), x ^ p ^ N = x := by
  classical
  set J := (maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (integralClosure ℤ_[p] L)) with hJ
  -- `J ≠ ⊤`: it is contained in a prime lying over `maximalIdeal ℤ_[p]`
  have hJtop : J ≠ ⊤ := by
    obtain ⟨Q, -, hQ, hQc⟩ := Ideal.exists_ideal_over_prime_of_isIntegral (maximalIdeal ℤ_[p])
      (⊥ : Ideal (integralClosure ℤ_[p] L))
      (Ideal.comap_bot_le_of_injective _ (algebraMap_Zp_integralClosure_injective p L))
    have hle : J ≤ Q := Ideal.map_le_iff_le_comap.2 hQc.ge
    exact ne_top_of_le_ne_top hQ.ne_top hle
  have : Nontrivial ((integralClosure ℤ_[p] L) ⧸ J) := Ideal.Quotient.nontrivial_iff.2 hJtop
  let _ : Field (ℤ_[p] ⧸ maximalIdeal ℤ_[p]) := Ideal.Quotient.field _
  have hfin : Finite (ℤ_[p] ⧸ maximalIdeal ℤ_[p]) :=
    Finite.of_equiv (ZMod p) PadicInt.residueField.symm.toEquiv
  have : Module.Finite ℤ_[p] (integralClosure ℤ_[p] L) :=
    IsIntegralClosure.finite ℤ_[p] ℚ_[p] L _
  have : Module.Finite ℤ_[p] ((integralClosure ℤ_[p] L) ⧸ J) :=
    Module.Finite.of_surjective (Ideal.Quotient.mkₐ ℤ_[p] J).toLinearMap
      Ideal.Quotient.mk_surjective
  have : Module.Finite (ℤ_[p] ⧸ maximalIdeal ℤ_[p]) ((integralClosure ℤ_[p] L) ⧸ J) :=
    Module.Finite.of_restrictScalars_finite ℤ_[p] _ _
  have : Algebra.EssFiniteType (ℤ_[p] ⧸ maximalIdeal ℤ_[p]) ((integralClosure ℤ_[p] L) ⧸ J) :=
    have := Module.Finite.finiteType (R := ℤ_[p] ⧸ maximalIdeal ℤ_[p])
      ((integralClosure ℤ_[p] L) ⧸ J)
    Algebra.EssFiniteType.of_finiteType _ _
  have : Algebra.FormallyUnramified (ℤ_[p] ⧸ maximalIdeal ℤ_[p])
      ((integralClosure ℤ_[p] L) ⧸ J) :=
    Algebra.FormallyUnramified.quotient_map _ _
  have hred : IsReduced ((integralClosure ℤ_[p] L) ⧸ J) :=
    Algebra.FormallyUnramified.isReduced_of_field (ℤ_[p] ⧸ maximalIdeal ℤ_[p]) _
  have hchar : CharP (ℤ_[p] ⧸ maximalIdeal ℤ_[p]) p :=
    charP_of_injective_ringHom (f := PadicInt.residueField.symm.toRingHom)
      PadicInt.residueField.symm.injective p
  have hcharA : CharP ((integralClosure ℤ_[p] L) ⧸ J) p :=
    charP_of_injective_algebraMap
      (algebraMap (ℤ_[p] ⧸ maximalIdeal ℤ_[p]) ((integralClosure ℤ_[p] L) ⧸ J)).injective p
  have hfinA : Finite ((integralClosure ℤ_[p] L) ⧸ J) :=
    Module.finite_of_finite (ℤ_[p] ⧸ maximalIdeal ℤ_[p])
  -- Frobenius is a permutation of the finite reduced ring `𝒪_L / J`
  have hbij : Function.Bijective (frobenius ((integralClosure ℤ_[p] L) ⧸ J) p) :=
    Finite.injective_iff_bijective.1 (frobenius_inj _ p)
  let σ : Equiv.Perm ((integralClosure ℤ_[p] L) ⧸ J) := Equiv.ofBijective _ hbij
  refine ⟨orderOf σ, orderOf_pos σ, fun x => ?_⟩
  have h1 : (σ ^ orderOf σ) x = x := by rw [pow_orderOf_eq_one]; rfl
  rwa [Equiv.Perm.coe_pow, Equiv.coe_ofBijective, iterate_frobenius] at h1

/-- **Teichmüller representatives in `𝒪_L`** (Hensel's lemma): if `x ^ (p ^ N) = x` on
`𝒪_L / p 𝒪_L` with `N ≥ 1`, every `x ∈ 𝒪_L` is congruent modulo `p 𝒪_L` to a root of
`X ^ (p ^ N) - X`. -/
theorem exists_pow_eq_self_sub_mem {N : ℕ} (hN : 0 < N)
    (hpow : ∀ x : (integralClosure ℤ_[p] L) ⧸
      (maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (integralClosure ℤ_[p] L)), x ^ p ^ N = x)
    (x : integralClosure ℤ_[p] L) :
    ∃ t : integralClosure ℤ_[p] L, t ^ p ^ N = t ∧
      x - t ∈ (maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (integralClosure ℤ_[p] L)) := by
  have hp1 : 1 < p := (Fact.out : Nat.Prime p).one_lt
  have hq1 : 1 < p ^ N := Nat.one_lt_pow hN.ne' hp1
  have hcomplete := integralClosure.isAdicComplete_map_maximalIdeal p L
  have hhens : HenselianRing (integralClosure ℤ_[p] L)
      ((maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (integralClosure ℤ_[p] L))) :=
    IsAdicComplete.henselianRing _ _
  have hp0 : ((p : ℕ) : (integralClosure ℤ_[p] L) ⧸
      (maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (integralClosure ℤ_[p] L))) = 0 := by
    have := Ideal.Quotient.eq_zero_iff_mem.2 (natCast_p_mem_map_maximalIdeal p L)
    rwa [map_natCast] at this
  have hq0 : ((p ^ N : ℕ) : (integralClosure ℤ_[p] L) ⧸
      (maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (integralClosure ℤ_[p] L))) = 0 := by
    rw [Nat.cast_pow, hp0, zero_pow hN.ne']
  have hmonic : (X ^ p ^ N - X : Polynomial (integralClosure ℤ_[p] L)).Monic :=
    Polynomial.monic_X_pow_sub (by rw [Polynomial.degree_X]; exact_mod_cast hq1)
  have heval : (X ^ p ^ N - X : Polynomial (integralClosure ℤ_[p] L)).eval x ∈
      (maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (integralClosure ℤ_[p] L)) := by
    rw [← Ideal.Quotient.eq_zero_iff_mem, Polynomial.eval_sub, Polynomial.eval_pow,
      Polynomial.eval_X, map_sub, map_pow, hpow, sub_self]
  have hderiv : IsUnit (Ideal.Quotient.mk
      ((maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (integralClosure ℤ_[p] L)))
      ((X ^ p ^ N - X : Polynomial (integralClosure ℤ_[p] L)).derivative.eval x)) := by
    rw [Polynomial.derivative_sub, Polynomial.derivative_X_pow, Polynomial.derivative_X,
      Polynomial.eval_sub, Polynomial.eval_mul, Polynomial.eval_C, Polynomial.eval_pow,
      Polynomial.eval_X, Polynomial.eval_one, map_sub, map_mul, map_natCast, hq0, zero_mul,
      zero_sub, map_one]
    exact isUnit_one.neg
  obtain ⟨t, ht, htx⟩ := hhens.is_henselian _ hmonic x heval hderiv
  refine ⟨t, ?_, ?_⟩
  · rw [Polynomial.IsRoot.def, Polynomial.eval_sub, Polynomial.eval_pow, Polynomial.eval_X,
      sub_eq_zero] at ht
    exact ht
  · rw [← neg_sub]
    exact (Ideal.neg_mem_iff _).2 htx

/-- **Nakayama**: if `T : 𝒪_L → 𝒪_L` picks representatives modulo `p 𝒪_L`, the values of `T`
span `𝒪_L` over `ℤ_[p]`. -/
theorem top_le_span_of_sub_mem (T : integralClosure ℤ_[p] L → integralClosure ℤ_[p] L)
    (hT : ∀ x, x - T x ∈ (maximalIdeal ℤ_[p]).map (algebraMap ℤ_[p] (integralClosure ℤ_[p] L))) :
    (⊤ : Submodule ℤ_[p] (integralClosure ℤ_[p] L)) ≤ Submodule.span ℤ_[p] (Set.range T) := by
  have : Module.Finite ℤ_[p] (integralClosure ℤ_[p] L) :=
    IsIntegralClosure.finite ℤ_[p] ℚ_[p] L _
  refine Submodule.le_of_le_smul_of_le_jacobson_bot Module.Finite.fg_top
    (maximalIdeal_le_jacobson ⊥) ?_
  intro x _
  rw [Submodule.mem_sup]
  refine ⟨T x, Submodule.subset_span ⟨x, rfl⟩, x - T x, ?_, by abel⟩
  rw [Ideal.smul_top_eq_map, Submodule.restrictScalars_mem]
  exact hT x

/-- If the values of `T : 𝒪_L → 𝒪_L` span `𝒪_L` over `ℤ_[p]`, they generate `L` over
`ℚ_[p]`. -/
theorem adjoin_range_eq_top_of_top_le_span
    (T : integralClosure ℤ_[p] L → integralClosure ℤ_[p] L)
    (hspan : (⊤ : Submodule ℤ_[p] (integralClosure ℤ_[p] L)) ≤
      Submodule.span ℤ_[p] (Set.range T)) :
    IntermediateField.adjoin ℚ_[p] (Set.range fun x => (T x : L)) = ⊤ := by
  have : IsFractionRing (integralClosure ℤ_[p] L) L :=
    integralClosure.isFractionRing_of_finite_extension ℚ_[p] L
  set S : Set L := Set.range fun x => (T x : L) with hS
  have key : ∀ c : integralClosure ℤ_[p] L, (c : L) ∈ IntermediateField.adjoin ℚ_[p] S := by
    intro c
    have hc : c ∈ Submodule.span ℤ_[p] (Set.range T) := hspan Submodule.mem_top
    refine Submodule.span_induction
      (p := fun (c : integralClosure ℤ_[p] L) _ => (c : L) ∈ IntermediateField.adjoin ℚ_[p] S)
      ?_ ?_ ?_ ?_ hc
    · rintro _ ⟨x, rfl⟩
      exact IntermediateField.subset_adjoin _ _ ⟨x, rfl⟩
    · simp only [ZeroMemClass.coe_zero]
      exact zero_mem _
    · intro x y _ _ hx hy
      rw [Subalgebra.coe_add]
      exact add_mem hx hy
    · intro r x _ hx
      rw [Subalgebra.coe_smul, Algebra.smul_def, IsScalarTower.algebraMap_apply ℤ_[p] ℚ_[p] L]
      exact mul_mem (IntermediateField.algebraMap_mem _ _) hx
  rw [eq_top_iff]
  intro z _
  obtain ⟨a, b, -, rfl⟩ := IsFractionRing.div_surjective (A := integralClosure ℤ_[p] L) z
  exact div_mem (key a) (key b)

omit [FiniteDimensional ℚ_[p] L] [IsScalarTower ℤ_[p] ℚ_[p] L] in
/-- The minimal polynomial over `ℚ_[p]` of a root of `X ^ (p ^ N) - X` in `L` splits over
`ℚᵘⁿ_[p]`. -/
theorem minpoly_splits_of_pow_eq_self {N : ℕ} (hN : 0 < N) (t : integralClosure ℤ_[p] L)
    (ht : t ^ p ^ N = t) :
    ((minpoly ℚ_[p] (t : L)).map (algebraMap ℚ_[p] ℚᵘⁿ_[p])).Splits := by
  have hp1 : 1 < p := (Fact.out : Nat.Prime p).one_lt
  have hroot : Polynomial.aeval (t : L) (X ^ p ^ N - X : Polynomial ℚ_[p]) = 0 := by
    rw [map_sub, Polynomial.aeval_X_pow, Polynomial.aeval_X, ← Subalgebra.coe_pow, ht, sub_self]
  have hdvd := Polynomial.map_dvd (algebraMap ℚ_[p] ℚᵘⁿ_[p]) (minpoly.dvd ℚ_[p] _ hroot)
  rw [Polynomial.map_sub, Polynomial.map_pow, Polynomial.map_X] at hdvd
  exact (QpUn.splits_X_pow_sub_X p hN).of_dvd
    (FiniteField.X_pow_card_pow_sub_X_ne_zero ℚᵘⁿ_[p] hN.ne' hp1) hdvd

/-- **Maximality of `ℚᵘⁿ_[p]`.** Every finite extension `L` of `ℚ_[p]` whose ring of integers
`𝒪_L = integralClosure ℤ_[p] L` is (formally) unramified over `ℤ_[p]` admits a
`ℚ_[p]`-embedding into `ℚᵘⁿ_[p]`.

Proof sketch: `𝒪_L` is finite free over `ℤ_[p]`, hence `p`-adically complete and Henselian. By
unramifiedness `𝒪_L / p 𝒪_L` is a finite reduced `𝔽_p`-algebra, so `x ^ (p ^ N) = x` on it for
some `N ≥ 1`; Hensel's lemma lifts every residue class to a root of `X ^ (p ^ N) - X` in `𝒪_L`
(a Teichmüller representative). By Nakayama the Teichmüller representatives span `𝒪_L` over
`ℤ_[p]`, hence generate `L` over `ℚ_[p]`; each of them has minimal polynomial dividing
`X ^ (p ^ N) - X`, which splits over `ℚᵘⁿ_[p]`, so `L` embeds into `ℚᵘⁿ_[p]`. -/
theorem QpUn.nonempty_algHom_of_formallyUnramified
    [Algebra.FormallyUnramified ℤ_[p] (integralClosure ℤ_[p] L)] :
    Nonempty (L →ₐ[ℚ_[p]] ℚᵘⁿ_[p]) := by
  obtain ⟨N, hN, hpow⟩ := exists_pow_pow_eq_self_quotient p L
  choose T hTq hTJ using exists_pow_eq_self_sub_mem p L hN hpow
  have hspan := top_le_span_of_sub_mem p L T hTJ
  have hadj := adjoin_range_eq_top_of_top_le_span p L T hspan
  refine IntermediateField.nonempty_algHom_of_adjoin_splits ?_ hadj
  rintro _ ⟨x, rfl⟩
  exact ⟨IsIntegral.of_finite ℚ_[p] (T x : L), minpoly_splits_of_pow_eq_self p L hN (T x) (hTq x)⟩

/-- **Maximality of `ℚᵘⁿ_[p]`**, `Algebra.Unramified` form: every finite extension `L/ℚ_[p]`
whose ring of integers is an unramified `ℤ_[p]`-algebra embeds into `ℚᵘⁿ_[p]` over `ℚ_[p]`. -/
theorem QpUn.nonempty_algHom_of_unramified
    [Algebra.Unramified ℤ_[p] (integralClosure ℤ_[p] L)] :
    Nonempty (L →ₐ[ℚ_[p]] ℚᵘⁿ_[p]) :=
  QpUn.nonempty_algHom_of_formallyUnramified p L

end Maximality

end TrustworthyKedlaya
